### ISSUE TITLE
Gnome Shell crash

### ISSUE THREAD

**Issue by canalguada** [horst3180/Vertex-theme#10]
For what it worth, I post a PKGBUILD for your themes here : https://gist.github.com/canalguada/a88d424cc19060f75b7f
Will also try to maintain a package synced with your latest release in the AUR system for a while : https://aur.archlinux.org/packages/vertex-themes/ But if someone more experienced proposes, I can disown it.

Got Gnome-Shell crashes, even with gnome-shell-no-crash.css, using radeon open source driver.
Please feel free asking me whatever you may need to troubleshoot that issue, if you try to.

Thanks for providing such a gorgeous theme ;-)

**Comment by manuelbua** [comment]
I can consistently reproduce the crashes by having Gnome's notifications appear: to replicate, open Chrome, open something else in the foreground, then trigger a notification, for example open a console, write an url such as "http://google.com" and click on it to open it in the browser: as soon as the notification arrives i need to quickly put the Chrome window to the foreground else a crash occur.

Note that after two or more crashes, gnome-shell will usually restarts itself and also *disable* any extension currently enabled.

**Comment by canalguada** [comment]
No Gnome-Shell crashes with latest release.
Next stop : Gnome 3.16 next week.

Thanks again.

**Comment by horst3180** [comment]
Hmm, okay. I don't know what I did to fix it, but that's good to know.
