### ISSUE TITLE
Cant see Font on white Background

### ISSUE THREAD

**Issue by ADMeinhard** [horst3180/Vertex-theme#101]
Hey there!
Every time I want to type sth. in a searching bar, in for example duckduck
go or YouTube (see screen-shot) I cant see what i am typing. 
Only with the dark vertex theme though.
![font fail](https://cloud.githubusercontent.com/assets/12121089/7336594/7037ab2e-ec06-11e4-8a77-c924437ca346.png)

EDIT: I forgot to say, on Google Search it works nicely

I use elementary OS Freya (based on Ubuntu 14.04LTS)
-I have to say, that I'm quite new to Linux

Thank you :)

**Comment by horst3180** [comment]
That's a long standing firefox bug with dark themes, unfortunately. To fix this you can install the Vertex-Dark firefox theme from the `extra` folder. There are instructions on how to do this in the README.
It will look like this
![2015-04-26-134213_1366x768_scrot](https://cloud.githubusercontent.com/assets/8473629/7337056/88510368-ec1a-11e4-9ed1-15bbdd39edc0.png)
Make sure to disable your current theme for this to work correctly.

**Comment by ADMeinhard** [comment]
Thanks it works now perfectly <3.
Dude* I love you

(insert female version of"Dude" if you are female :D)*

**Comment by horst3180** [comment]
Thanks :)
(Yes, I'm a dude)
