### ISSUE TITLE
Suggestion: Unity Panel menu bar active/selection background

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#102]
I wonder if you would like to consider using the same active/selection/hover effect on the Unity panel as used in both gtk2 and gtk3 menu bars, i.e. just a grey outline with round top corners (Greybird theme has got something like this, without round top corners) instead of the current blue semi-transparent box?

**Comment by horst3180** [comment]
That would definitely be more consistent. I don't know why I styled the Unity panel differently.

**Comment by horst3180** [comment]
Now I remember why I styled it the way it is. If you use the default or dark variant of the theme, the indicator icons are light. When the active indicator has a white background, the icon becomes almost invisible.

**Comment by Sadi58** [comment]
Hmm, I thought you could make that box transparent with only a non-transparent outline :\)

**Comment by horst3180** [comment]
Maybe I misunderstood you, but the active menubar items look like this

![2015-04-26-182953_1366x768_scrot](https://cloud.githubusercontent.com/assets/8473629/7338136/8780c77a-ec42-11e4-8f00-e55c8f4438e3.png)

Or do you mean a different widget?

**Comment by Sadi58** [comment]
I have that menubar item in Vertex-Light only, whereas Vertex has a dark widget (same color as menubar) with sort of black outline.
I've just upgraded to Ubuntu 15.04 and also switch to Vertex 3.14 version.

**Comment by horst3180** [comment]
Ah, now I understand. I totally forgot that you can put the menubar into the window titles.

**Comment by horst3180** [comment]
I guess you mean something like this?
![ubuntu](https://cloud.githubusercontent.com/assets/8473629/7338608/b9cb142e-ec51-11e4-9f45-539f2327fc41.png)

**Comment by Sadi58** [comment]
Yes, exactly, and the same for SysTray items on the right as well...

**Comment by horst3180** [comment]
Yes, that uses the same style.

**Comment by Sadi58** [comment]
Thanks for fixing the Unity Top Panel menubar styling, but I'm sorry to inform you that it seems there's a minor problem with the build process for Vertex-Light, which now looks like Vertex-Dark.

**Comment by horst3180** [comment]
Can not confirm. Maybe you have to delete the theme manually and reinstall again.

**Comment by Sadi58** [comment]
Ooops, sorry, it's OK now. I don't know what happened.
I repeated the manual build & install, but this time deleted the remainin `gtk-dark.css` and `gtk-contained-dark-css`. Perhaps maybe this, maybe something else caused the problem.
Anyway, thank you so much...

**Comment by Sadi58** [comment]
For the record, I've found the cause:
Enabling "Global Dark Menu" in Gnome Tweak Teal resulted in using `gtk-dark.css` and `gtk-contained-dark-css'.
