### ISSUE TITLE
Cleaning after manual build & install

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#103]
If I haven't missed something, I see many unnecessary files in the target theme sub-directory `gtk-3.0` after manual build & install as per the `README.md` file, e.g. `*.txt`, `*.sh`, `*.scss` and `*dark*` files (also in `assets` sub-directory) in the Light version, and some others.

**Comment by horst3180** [comment]
That's true. I'm planning add some cleanup instructions to the build system to remove the unnecessary files.
The `*-dark` files in in the `assets` directory are actually used by the light theme for the dark mode. I know that Ubuntu doesn't use the dark mode very much, but some Gnome applications request a dark theme, like Totem, Gnome Photos, etc.
