### ISSUE TITLE
Mousepad search box is not themed correctly.

### ISSUE THREAD

**Issue by ali1234** [horst3180/Vertex-theme#105]
When you search for text in mousepad, the search box turns red if the text is not found. Under Vertex the background does not change colour, rendering the text invisible.

Screenshots:

![notfound-numix](https://cloud.githubusercontent.com/assets/651970/7386903/a6bee120-ee50-11e4-828a-2cad0a700391.png) (how it should look)

![notfound-vertex](https://cloud.githubusercontent.com/assets/651970/7386911/b91f57c8-ee50-11e4-9087-dbd2d47ab47a.png) (how it looks in vertex)

The code which controls the style of this textbox is here:

http://git.xfce.org/apps/mousepad/tree/mousepad/mousepad-util.c#n381

**Comment by horst3180** [comment]
This seems to be a regression introduced with 0a85f553f9adb73b1497af3bac4e2c305013a6c9. Reverting this commit should solve the problem.

**Comment by ali1234** [comment]
I just checked and reverting that commit does fix it.
