### ISSUE TITLE
CRX_MAGIC_NUMBER_INVALID - Vertex chromium

### ISSUE THREAD

**Issue by bratanon** [horst3180/Vertex-theme#106]
When adding vertex (extra/Chrome/Vertex.crx) to chromium, I get an error:

Package is invalid: 'CRX_MAGIC_NUMBER_INVALID'.

**Comment by horst3180** [comment]
Hm, doesn't happen to me. What is your Chromium version?

**Comment by bratanon** [comment]
Its Version 42.0.2311.135 (64-bit) running on Linux Arch

**Comment by bratanon** [comment]
Don't know if this helps, but the light version works perfect.

**Comment by horst3180** [comment]
I'm running the same chromium version, but strangely it works fine for me. I can try to rebuild the .crx package. That might fix the problem.

**Comment by bratanon** [comment]
Do you know if I have some way to debug this my self, and maybe provide this issue with more information?

**Comment by horst3180** [comment]
You could try to rebuild the crx. See here https://developer.chrome.com/extensions/packaging
The extension root directory mentioned in the link would be `extra/Chrome/source/Vertex` and you don't need to specify a private key.

**Comment by bratanon** [comment]
It works when I rebuild the crx file myself. 
Thanks.
