### ISSUE TITLE
[Firefox] about:config unreadable

### ISSUE THREAD

**Issue by samueljun** [horst3180/Vertex-theme#108]
![screenshot from 2015-06-01 00-46-48](https://cloud.githubusercontent.com/assets/1808588/7908303/9aee22b8-07f8-11e5-83ad-af96da48750a.png)

Arch Linux
Gnome 3.16.2
Vertex-theme Release 20150425

Using "Global Dark Theme", "Vertex-Dark" for GTK+, and Vertex-Dark theme for Firefox

**Comment by horst3180** [comment]
Should be fixed with dfa777f2edac3d24e2839880f0939065f614e150.
