### ISSUE TITLE
Buttons minimize, maximize, close don't appear

### ISSUE THREAD

**Issue by ivanimatrix** [horst3180/Vertex-theme#109]
Buttons minimize, maximize and close don't appear on gnome-shell 3.16
![captura de pantalla de 2015-06-02 11-58-37](https://cloud.githubusercontent.com/assets/560970/7938958/c05f3de4-091e-11e5-9aab-5640d712efa5.png)

**Comment by horst3180** [comment]
This is probably related to this https://github.com/horst3180/Vertex-theme/issues/107
