### ISSUE TITLE
[vertex-light] black loading-bars

### ISSUE THREAD

**Issue by Thor77** [horst3180/Vertex-theme#111]
In Hexchat are two connection-bars in the lower-right corner:
![img hexchat](https://cloud.githubusercontent.com/assets/4989736/8111284/31f18e82-1061-11e5-8190-73fbcbf18cd9.png)
i think they should be white.
The same error affects the gimp-loading bar (visible under the splash-image) after starting gimp.
![img gimp](https://cloud.githubusercontent.com/assets/4989736/8111330/7ffa7896-1061-11e5-9c71-febdb522d1d4.png)

**Comment by horst3180** [comment]
That's how it's supposed to look.
