### ISSUE TITLE
[vertex-light] thunderbird dark message-write-field

### ISSUE THREAD

**Issue by Thor77** [horst3180/Vertex-theme#112]
Just found another issue,
the text-field in the message-write-dialog from thunderbird has a black background with black text => messages are unreadable.
![screenshot](https://cloud.githubusercontent.com/assets/4989736/8130025/90bc3c10-110f-11e5-9779-e76c9689c862.png)

**Comment by horst3180** [comment]
I can't confirm this. It's working correctly for me.

**Comment by Thor77** [comment]
After removing my complete thunderbird-profile and applying the theme again, it works fine!
