### ISSUE TITLE
Buttons glitch

### ISSUE THREAD

**Issue by solbjorn** [horst3180/Vertex-theme#114]
Can't tell if it's Gnome Shell or Vertex issue, but this randomly occurs on startup. It does not affect windows with custom headerbar, only classic (both GTK2 & 3). GTK3 3.16.4, GNOME 3.16.2, Arch Linux x64.
![2015-07-02 10-37-09](https://cloud.githubusercontent.com/assets/12006295/8477045/99c9a610-20cf-11e5-8754-b907b2e550b3.png)

**Comment by horst3180** [comment]
That's a mutter bug. See [here](https://bugs.archlinux.org/task/44741?string=gnome&project=1&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=).

**Comment by solbjorn** [comment]
Ok, thanks.

**Comment by horst3180** [comment]
The bug seems to be fixed upstream, so we'll have to wait for mutter 3.16.3.
