### ISSUE TITLE
[vertex-light] misaligned text in GTK2 theme

### ISSUE THREAD

**Issue by Narrat** [horst3180/Vertex-theme#117]
Following situation with Thunar:
![1](https://cloud.githubusercontent.com/assets/2787518/8872640/2d63a34a-31ff-11e5-9f69-83c82ce80a12.png)

![2](https://cloud.githubusercontent.com/assets/2787518/8872657/4b05cc02-31ff-11e5-9e1a-109da06b3ce2.png)
Now going a folder up and the text is leftaligned until
![3](https://cloud.githubusercontent.com/assets/2787518/8872661/5aa4872a-31ff-11e5-8fd4-fad6c5a5937a.png)
I do a mouse-over that button or anything else that triggers some kind of reload.

I didn't notice such behaviour with the zukitwo theme, so is this from the theme, or something else that could misbehave?

**Comment by horst3180** [comment]
That seems to be a bug in the pixmap engine, because it seems to happen mainly with pixmap themes (including Adwaita).
It doesn't look like it's fixable at theme level.
