### ISSUE TITLE
Libreoffice 5 dark toolbars

### ISSUE THREAD

**Issue by Tead** [horst3180/Vertex-theme#122]
The toolbars in Libreoffice 5 are dark after an automatic upgrade on Archlinux.

![libreoffice5_dark](https://cloud.githubusercontent.com/assets/574789/9174432/05b5eb26-3f80-11e5-808d-28c0ef161976.png)
(Libreoffice 5 top vs Libreoffice 4 down)

I think the light toolbars as in Libreoffice 4 are better.

**Comment by horst3180** [comment]
Libreoffice 5 comes with initial gtk3 support which is still incomplete and buggy. I can't do much at this point to fix this. We'll have to wait for a new libreoffice release in which those things are hopefully fixed.

**Comment by Tead** [comment]
Ok, thank you for your answer.

Shall I close this issue or do you want to keep it open for other people with the same issue?

**Comment by tobias-haenel** [comment]
Just uncomment the line <code>#export SAL_USE_VCLPLUGIN=gtk</code>
in "/etc/profile.d/libreoffice-fresh.sh" and the old look (without gtk3 support) will be used
