### ISSUE TITLE
Firefox window control buttons in fullscren mode and with firefox-extension-htitle

### ISSUE THREAD

**Issue by vantu5z** [horst3180/Vertex-theme#123]
Find that window control buttons in fullscren mode and with firefox-extension-htitle looks like this:
![2015-08-11 20-00-50](https://cloud.githubusercontent.com/assets/8698003/9204409/d483c5e6-4065-11e5-879a-ee9762c77d40.png)
Developer of "seleznev/firefox-extension-htitle" find that it is not Htitle issue.

**Comment by danielsanfr** [comment]
Also here :(

**Comment by horst3180** [comment]
Should be fixed with https://github.com/horst3180/Vertex-theme/commit/c0cb9be28f01e5d418f35f3feab1ea61695ef239

**Comment by vantu5z** [comment]
Thanks, now it's good :)
