### ISSUE TITLE
Ubuntu Software Center not readable text

### ISSUE THREAD

**Issue by kapcom01** [horst3180/Vertex-theme#127]
Hello, I have Ubuntu 15.04 with `ubuntu-gnome-desktop` installed. Everything is so beautiful that even with this problem I am still going to keep the theme :+1: 
Anyway I thought I should report it. Here is a screenshot.
Thanks for the theme
![______________________ ______ 2015-08-28 01_04_15](https://cloud.githubusercontent.com/assets/21684/9534486/67802e8a-4d21-11e5-9992-a736ba741c00.png)
!
![______________________ ______ 2015-08-28 01_12_13](https://cloud.githubusercontent.com/assets/21684/9534571/03233ddc-4d22-11e5-9466-9aa5ab08c2b7.png)
![______________________ ______ 2015-08-28 01_12_17](https://cloud.githubusercontent.com/assets/21684/9534572/035ae62e-4d22-11e5-9489-568b0302d921.png)

**Comment by horst3180** [comment]
I assume that you're using the dark theme? You can find a fix for the Ubuntu Software Center In the `extra` directory of the repository. Just follow the README and it should work.

https://github.com/horst3180/Vertex-theme/tree/master/extra/Ubuntu-Software-Center

**Comment by kapcom01** [comment]
Yes I have seen this workaround. I thought if there is a solution without having to modify files.

**Comment by horst3180** [comment]
Yea, it's a bit ugly, but it's the only way to change the colors the Ubuntu Software Center since they are hardcoded in the `softwarecenter.css` by default. That css file will override whatever the theme sets.
It's really a Ubuntu Software Center bug.

**Comment by kapcom01** [comment]
Ok then I get it now. Thanks!
