### ISSUE TITLE
Existence of a border at points of the menu

### ISSUE THREAD

**Issue by kosas** [horst3180/Vertex-theme#128]
Ubuntu 14.04.03 Theme - Vertex

All elements in windows the border is observed
![kosas-book_002](https://cloud.githubusercontent.com/assets/2162152/9567557/8d595a6e-4f38-11e5-9092-2e4f859d674c.png)
![kosas-book_003](https://cloud.githubusercontent.com/assets/2162152/9567558/9950ef30-4f38-11e5-9e6a-59960ac73032.png)

**Comment by horst3180** [comment]
How did you install the theme? It looks like you have picked the package for a newer Ubuntu version.
This should fix it:

    sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/vertex-theme.list"
    sudo apt-get update
    sudo apt-get install vertex-theme

If you installed the package manually, I think you might be missing `pkg-config`.

**Comment by kosas** [comment]
Thanks! Everything rose on the places.
