### ISSUE TITLE
Graphics issue (Ubuntu 14.04)

### ISSUE THREAD

**Issue by kalpetros** [horst3180/Vertex-theme#130]
There is a dotted border around buttons, windows etc almost in the entire system as seen below.

I installed the theme manually by doing the following:
`./autogen.sh --prefix=/usr`
`sudo make install`

![vertex](https://cloud.githubusercontent.com/assets/5626758/9667341/e2f0a506-5283-11e5-97bf-ab4605464a18.png)

**Comment by Narrat** [comment]
I suppose this fits with those:
https://github.com/horst3180/Vertex-theme/issues/128
https://github.com/horst3180/Vertex-theme/issues/118

**Comment by kalpetros** [comment]
I fixed it doing the following:
`sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/vertex-theme.list"`
`sudo apt-get update`
`sudo apt-get install vertex-theme`
