### ISSUE TITLE
[3.18][vertex] gnome-terminal 3.18 glitches

### ISSUE THREAD

**Issue by solbjorn** [horst3180/Vertex-theme#132]
Gnome terminal (version 3.17.93 built with fedora patches) now looks like this if opened more than one tab:
![2015-09-16 20-38-17](https://cloud.githubusercontent.com/assets/12006295/9912981/08ec5c12-5cb3-11e5-801e-f6c815fd0520.png)
As i know, this added functional will be presented in 3.18 official release.

**Comment by horst3180** [comment]
Gnome 3.18 support has been added. It does now work with gnome-terminal 3.18.0

**Comment by solbjorn** [comment]
OK, closing.

**Comment by horst3180** [comment]
Yes, I'll do that.

**Comment by solbjorn** [comment]
Many thanks, great!
