### ISSUE TITLE
period lines

### ISSUE THREAD

**Issue by JorchMantilla** [horst3180/Vertex-theme#135]
With the new update i get a bug like I show in the pic

![captura de pantalla de 2015-09-23 22 29 52](https://cloud.githubusercontent.com/assets/1315282/10064864/1ceb584a-6243-11e5-8ff9-99f5fb95a91e.png)

ubuntu 14.04.3 with unity

**Comment by horst3180** [comment]
Did you install the theme manually? If yes, make sure you have `pkg-config` and `libgtk-3-dev` installed.

**Comment by JorchMantilla** [comment]
Hello, I used the repo

**Comment by horst3180** [comment]
Maybe you picked the wrong repo, i.e. for a newer Ubuntu version?

You could do `cat /etc/apt/sources.list.d/vertex-theme.list`. If it contains something like `xUbuntu_14.10` or `xUbuntu_15.04` in the output, you picked the wrong repo.

You can fix this with

    sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/vertex-theme.list"
    sudo apt-get update
    sudo apt-get install vertex-theme

**Comment by JorchMantilla** [comment]
I am going to try ok

**Comment by JorchMantilla** [comment]
thats the output of: cat /etc/apt/sources.list.d/vertex-theme.list

deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_14.04/
/


2015-09-28 17:59 GMT-05:00 jorge mantilla <jhmb666@gmail.com>:

> I am going to try ok

**Comment by JorchMantilla** [comment]
ok, I eresed the repo and the packages ...and voila! .... everything is working again ...thanks

**Comment by horst3180** [comment]
Ah, good to know. I'm not sure what went wrong there :)
