### ISSUE TITLE
Volume control not working on 15.04

### ISSUE THREAD

**Issue by diogoleitao** [horst3180/Vertex-theme#136]
Just installed the theme and unfortunately the blue volume control icons (the overlays, not the ones on the top bar) don't work. I don't know if they're missing (haven't find the files yet) or if there's a problem integrating those icons. All else (as far as I've tested) is working fine.

I'm running Ubuntu with GNOME desktop (GNOME Shell 3.14.4) and I installed the theme via http://goo.gl/ybhzSZ.

Cheers

**Comment by horst3180** [comment]
I'm not sure what you're referring to. Could you post a screenshot?

**Comment by diogoleitao** [comment]
![screenshot from 2015-09-28 23 37 04](https://cloud.githubusercontent.com/assets/5692154/10150839/e7ae4c5a-6639-11e5-83e9-bef88bc23be8.png)

Compared to your volume icon (that shows on this repo's main page), it's completely different.
Unless it's related to the fallback theme for the icons, but I don't think it is (is it?).

**Comment by horst3180** [comment]
You have to use Vertex as Gnome-Shell theme to get the blue bar.

**Comment by diogoleitao** [comment]
How do you do that, then? Sorry I'm asking so many questions but I had all the configurations on my other machine, lost them and can't recall what and how I did it.

**Comment by horst3180** [comment]
You can do that with gnome-tweak-tool. You have to select Vertex as Shell theme under the Appearance section.
Or just do `gsettings set org.gnome.shell.extensions.user-theme name Vertex
`

**Comment by diogoleitao** [comment]
Sorry, I hadn't turned on the user shell themes. You can close this issue. Thank you for your help!
