### ISSUE TITLE
Small icon hdpi screen

### ISSUE THREAD

**Issue by MalcolmMielle** [horst3180/Vertex-theme#139]
Hi,

I don't think the "close" icon is scaled with hdpi screen and it's really small :/. 
See on this image in the top right of my screen

![screenshot from 2015-10-05 16 12 54](https://cloud.githubusercontent.com/assets/4457840/10282593/0038b228-6b7c-11e5-9f3a-d9bb2ba02156.png)

**Comment by horst3180** [comment]
It should be fixed now.
