### ISSUE TITLE
Progress Pie is hard to see [Gnome 3.18]

### ISSUE THREAD

**Issue by ainola** [horst3180/Vertex-theme#142]
Thanks for such an amazing theme!

![screenshot from 2015-10-19 20-59-02](https://cloud.githubusercontent.com/assets/5383525/10596729/78f5f9e0-76a4-11e5-9ba2-77e2d88370d1.png)

**Comment by horst3180** [comment]
Unfortunately that icon color is hardcoded, so it's impossible to change from the theme.

**Comment by ainola** [comment]
That's too bad. Thanks for the quick response, and thanks again for the great theme.

**Comment by ainola** [comment]
Looks like the latest version of Files allows themers to take control over the pie colors, now!

https://git.gnome.org/browse/nautilus/commit/?id=b2d37a0523507cb3fc0b3d3e95048a91eb54b6ba

**Comment by horst3180** [comment]
Did you test it with Nautilus 3.18.2? The upstream patch looks like the progress thingy now uses the icon color, so no theme modifications are needed.

**Comment by ainola** [comment]
*awkward cough*

Yeah, I hadn't restarted nautilus since the 3.18.2 upgrade. It looks lovely. Apologies for all the noise!
