### ISSUE TITLE
Cinnamon theme is buggy on grid expo mode

### ISSUE THREAD

**Issue by Pival81** [horst3180/Vertex-theme#145]
the cinnamon shell theme is buggy when used in expo mode with grid activated
![menu_008](https://cloud.githubusercontent.com/assets/15673222/10974211/4b669c06-83e1-11e5-83ea-bcdadfce8104.png)

**Comment by horst3180** [comment]
Fixed with https://github.com/horst3180/Vertex-theme/commit/b75416aa44ff54499898f0c7d93ef91565df54d1.
