### ISSUE TITLE
Cinnamon 2.8 - new audio/volume menu applet

### ISSUE THREAD

**Issue by entr** [horst3180/Vertex-theme#146]
As you can see the new cover image is overflowing the dropdown.

![vertex-cinnamon-28](https://cloud.githubusercontent.com/assets/191571/11014279/ff8cfd68-8537-11e5-80ec-6da4fc1e9eaa.jpg)

Also the first row might need some padding.

**Comment by horst3180** [comment]
Fixed with https://github.com/horst3180/Vertex-theme/commit/b75416aa44ff54499898f0c7d93ef91565df54d1.
