### ISSUE TITLE
Strange coloring for buttons in some dialogs and left side menu 

### ISSUE THREAD

**Issue by oterner** [horst3180/Vertex-theme#147]
First, thanks for great theme.

I have strange coloring on some dialogs (shutdown, alt-f2) and left side menus (files, gnome-tweak-tool). All other UI looks just like at picture.
![strange_buttons](https://cloud.githubusercontent.com/assets/10072022/11033716/31d9c334-86ee-11e5-9225-b12b44b6ef73.jpg)

![files](https://cloud.githubusercontent.com/assets/10072022/11033851/6a88d962-86ef-11e5-9c07-4bc2775de4c0.jpg)

My env is: Ububtu 15.10, Gnome 3.18, Vertex 1442960975.ba52012

If not a bug sorry for disturbing...

**Comment by horst3180** [comment]
You have to install the theme manually. The package doesn't work properly, because it's made for Gnome 3.16.

**Comment by oterner** [comment]
Thanks for update.
Build from sources for gnome-3.18 fixes all this.
