### ISSUE TITLE
Weird borders and invisible interfaces on certain Linux Mint built-in applications.

### ISSUE THREAD

**Issue by PJB3005** [horst3180/Vertex-theme#151]
So, I will say I absolutely love this theme, however I've been having some issues with applications on Linux Mint, I have however seen that all issues are isolated to programs that come with Linux Mint.

So first, there's borders:

![](http://i.imgur.com/oR0VCCG.jpg)

Lots of them.

Now that's not really a big issue, what is, is this:

![](http://i.imgur.com/bfs8HwE.jpg)

And those only appeared when I initially hovered over them, too.

And it gets even worse:

![](http://i.imgur.com/LRIIUxO.jpg)

**Comment by Narrat** [comment]
There were some reports about borders. https://github.com/horst3180/Vertex-theme/issues/130
IIRC mainly a reason of using the wrong theme version against the locally installed gtk version

So I suppose it could be helpful to post information about the gtk version and how you installed the theme

**Comment by PJB3005** [comment]
Yep that was the issue, derp.

**Comment by Zero3** [comment]
@PJB3005 I'm having the same issue with the latest Linux Mint Cinnamon (13.3). Would you mind explaining how you fixed it?
