### ISSUE TITLE
Gnome Shell's window list isn't styled.

### ISSUE THREAD

**Issue by trusktr** [horst3180/vertex-theme#156]
Screenshot (panel at the bottom):

![screenshot from 2015-12-08 18-36-29](https://cloud.githubusercontent.com/assets/297678/11674982/a7127724-9dda-11e5-890c-037914785a19.png)

The window list is one of Gnome's default extensions. It'd be nice if you styled that too, as the default one is so ugly! x]

**Comment by voyagerok** [comment]
I would recommend to open /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/stylesheet.css and change background color in section .window-button > StWidget to transparent. It will look much better.

**Comment by voyagerok** [comment]
Screen for example
![desktop](https://cloud.githubusercontent.com/assets/8675227/11827983/64ddb4fa-a3a1-11e5-99bc-496b20b85a7d.jpg)

**Comment by trusktr** [comment]
Aaaah, much better. The changes wouldn't always show up until I logged out and back in (alt+f2/r wasn't enough).

I just tried he inspector, but it wasn't obvious how to determine the class names of the things I was inspecting. Do you know the trick to that?

**Comment by horst3180** [comment]
This is impossible to fix from within the theme, hence I'm closing this.

**Comment by trusktr** [comment]
@horst3180 Why is that?

**Comment by horst3180** [comment]
It's because the window-list extension overrides the theme with its own [stylesheet](https://git.gnome.org/browse/gnome-shell-extensions/tree/extensions/window-list/stylesheet.css).

**Comment by trusktr** [comment]
@horst3180 So CSS in Gnome isn't similar to CSS in the web where a global style can affect any element?
