### ISSUE TITLE
Song info box out of container - Sound Applet - Cinnamon 2.8.6

### ISSUE THREAD

**Issue by jeronimonavarro** [horst3180/Vertex-theme#160]
![bug1](https://cloud.githubusercontent.com/assets/13712031/11933107/890e3c6a-a7d8-11e5-9ea8-c591f58fdc15.png)

The current song information +  controls are out of the limits of the applet.
Tested in 2 different machines with same OS and configuration.

OS: openSUSE Leap 42.1
DE: Cinnamon 2.8.6
GTK+: 3.16

**Comment by entr** [comment]
Duplicate of #146 - fixed

**Comment by jeronimonavarro** [comment]
Thanks, I was using the prebuilt package for openSUSE which doens't include that commit. 
Building from source solved it.
