### ISSUE TITLE
./autogen.sh --prefix=/usr

### ISSUE THREAD

**Issue by erikdubois** [horst3180/Vertex-theme#162]
Is there a possibility to let the script install the themes in the local files  of the user rather than in usr/share/themes?

ps. article on http://erikdubois.be/how-to-completely-install-all-aspects-of-the-vertex-dark-theme-on-linux-mint-17-3/ has been changed

the alternative metacity theme is that something for Linux MInt 17.3?

Software center css ?? is this for linux mint 17.3 applicable?

**Comment by erikdubois** [comment]
sudo add-apt-repository ppa:noobslab/themes -y
sudo apt-get update
sudo apt-get install vertex-theme -y

also a possibility to install it

**Comment by horst3180** [comment]
You can install locally with `./autogen.sh --prefix=/home/you_user_name/.local`. That will install the theme to `~/.local/share`. Although that might cause some issues.

The software center css is a workaround for the Ubuntu Software Center with dark themes. So if you don't have Ubuntu Software Center, you don't need it.
The alternative metacity theme is similar to the default metacity theme, but it hides the titlebar in maximized windows, it should work with Mint.

**Comment by erikdubois** [comment]
thanks

**Comment by der-Daniel** [comment]
thanks!
