### ISSUE TITLE
Dodgy side panel on Files (nautilus) 3.18.4

### ISSUE THREAD

**Issue by virtualfunction** [horst3180/vertex-theme#164]
My font sizes are a bit different due to my HiDPI screen settings, but this seems like a theme issue as Adwaita looks fine 

![OK in Adwaita](http://jason.virtualfunction.net/nautilus_ok.png)

But as you can see my whitespace looks odd. Also the Eject probably shouldn't have button styling/bevels?

![OK in Adwaita](http://jason.virtualfunction.net/nautilus_f__ked.png)

**Comment by horst3180** [comment]
It looks like you installed the wrong version of the theme. How did you install it and what's your distro?

**Comment by virtualfunction** [comment]
I'm running Xenial (I had some issues with 15.10 so just thought I've switch to Xenial and other than this have found it to be pretty solid) - Obviously you don't have DEB's for it so I used the wily debs here http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.10/all/vertex-theme_1442960975.ba52012_all.deb - I've sort of skirted round the issue by using GDM_THEME=Adwaita nautilus in my shortcuts for now

**Comment by horst3180** [comment]
Yeah, the deb for 15.10 is made for Gnome 3.16. You can fix this by removing the package and install the theme manuall with

    sudo apt-get remove vertex-theme
    sudo apt-get install autoconf automake
    ./autogen.sh --prefix=/usr --with-gnome=3.18
    sudo make install

**Comment by virtualfunction** [comment]
Ah cool - Done that (except shoved in my $HOME/.themes dir and it all works fine :)
