### ISSUE TITLE
Non-standard  --no-preserve cp flag in Makefile

### ISSUE THREAD

**Issue by Scarletts** [horst3180/vertex-theme#169]
See [small hitch installing on FreeBSD](https://github.com/horst3180/arc-theme/issues/362). This is fixed for the Arc theme but not Vertex or Ceti-2 :(

btw, I'm using these themes on an Xfce desktop running NetBSD.

They look great, but I admit, I installed them by copying files into the right place manually instead of using the build system, mostly out of lack of patience for autotools. So there might be more problems installing these on a BSD system besides the cp(1) flag. After removing the flag only the index.theme file was getting installed (or I'm just stupid and doing the wrong thing).

**Comment by horst3180** [comment]
You're right, I removed the flag now. It should work, but you have to run `autogen.sh` again, or reinstall from a newly cloned repository.
