### ISSUE TITLE
gnome-shell theme not working on centos 7.2

### ISSUE THREAD

**Issue by msowka** [horst3180/vertex-theme#170]
I've build and installed the rpm from the fedora 23 repo found [here](http://download.opensuse.org/repositories/home:/Horst3180/Fedora_23/src/). Everything seemed to work correctly except for the gnome-shell theme where the top bar and bottom bar w/ window list don't seem to be styled as expected at all, see shot.

I have tried logging out and logging back in. Centos 7.2 comes with Gnome 3.14. I do see there is some tips on polishing gnome-shell window list styling in issue #156, but this seems to be more severe breakage.

![screenshot from 2016-03-08 01-04-53](https://cloud.githubusercontent.com/assets/1069078/13593613/c7830654-e4ca-11e5-9f14-2ccbb9a69c3a.png)

**Comment by voyagerok** [comment]
Have you tried to start a standart GNOME 3 session instead of classic mode? You can choose session in GDM while logging in.

**Comment by msowka** [comment]
Voyagorek, you are right, the theme applies to the standard Gnome 3 desktop. This should be then an 'improvement', ie to style the Classic panels of the default CentOS session.
