### ISSUE TITLE
Epiphany Issue (Gnome 3.20): Tabs and progressbar are unthemed

### ISSUE THREAD

**Issue by columna** [horst3180/vertex-theme#175]
Here's a screenshot:

![epiphany](https://cloud.githubusercontent.com/assets/12877777/14253847/7c4f6622-fa8d-11e5-9499-aa5345efa647.png)

**Comment by horst3180** [comment]
That's basically the same as https://github.com/horst3180/vertex-theme/issues/173. With GTK 3.20 you can't apply application specific styles as easily anymore.
It only works if the application provides a unique style class or something that I can target. Nautilus does this for example by adding the `nautilus-window` style class to its toplevel window.

**Comment by columna** [comment]
Okay, thanks for the quick answer. 
Then let us hope there'll be a way, sooner or later ;)
