### ISSUE TITLE
Totem Issue (Gnome 3.20): The buttons right from the seekbar

### ISSUE THREAD

**Issue by columna** [horst3180/vertex-theme#176]
Here's a screenshot:

![totem](https://cloud.githubusercontent.com/assets/12877777/14254977/64ea4600-fa92-11e5-8b5d-b7530c0f4e54.png)

I guess hiding the button-frame will do the trick ;)

Unless it's hardcoded like the new tabs, download-button etc...

**Comment by horst3180** [comment]
I can add a margin to the buttons like this:
![totem](https://cloud.githubusercontent.com/assets/8473629/14256815/0153a4d4-fa9b-11e5-90f1-48a8b719648a.png)

**Comment by horst3180** [comment]
Oh, and it is a flat button, so it shouldn't have a border. I fixed that too.

**Comment by columna** [comment]
Wow, that was quick! Everything's fine again.
Thank you very much for your great work. Love your themes!
