### ISSUE TITLE
packaging vertex firefox theme

### ISSUE THREAD

**Issue by fossfreedom** [horst3180/vertex-theme#179]
Hi,

  with our distro budgie-remix we are shipping with the vertex-theme.

We are also thinking about packaging the extras/firefox themes - possibly/probably along the lines of arc-firefox-theme.

Obviously we need a install.rdf file for each theme.  Question - did you have plans yourself to create xpi packages?

**Comment by horst3180** [comment]
Hmm, currently i don't have any plans to convert it into an xpi theme.
I'd probably do it if it was a one time effort, but complete firefox themes are a pain to maintain. You basically have to rebase the whole thing on the default theme every six weeks to make it work properly with new firefox versions.

**Comment by fossfreedom** [comment]
okey-dokey - thanks that make sense.  Cheers for the info.
