### ISSUE TITLE
[Vertex-Dark] Thunderbird tabs

### ISSUE THREAD

**Issue by oberon2007** [horst3180/vertex-theme#184]
The screenshot says it all :wink: 

![thunderbird](https://cloud.githubusercontent.com/assets/11800714/14670078/de72fa16-06eb-11e6-8e87-ba1883c87577.png)

**Comment by oberon2007** [comment]
I'm using https://github.com/horst3180/vertex-theme/commit/6c6cfdbaadb04fb2ccf3c8cf11ffcee84873af2f with **gtk2 2.24.30** and **thunderbird 45.0**

**Comment by kouros17** [comment]
I confirm it.

![_2016-04-20_14-40-55](https://cloud.githubusercontent.com/assets/3219560/14673315/f6b1a3b0-0705-11e6-98fd-15d46b2ac7f3.png)

**Comment by FadeMind** [comment]
![screenshot_20160420_140750](https://cloud.githubusercontent.com/assets/9846948/14673960/4be3d29a-0701-11e6-8034-aa0df866bc23.png)
CLICK for open screenshot in new tab for full size.

**Comment by oberon2007** [comment]
The issue has disappeared with **thunderbird 45**
