### ISSUE TITLE
It doesn't work on Ubuntu Gnome 16.04 updated Gnome to 3.20

### ISSUE THREAD

**Issue by nihild3v** [horst3180/vertex-theme#189]
Very ugly, why?
![screenshot from 2016-05-01 07-28-56](https://cloud.githubusercontent.com/assets/16595122/14941599/ee06ca66-0f6a-11e6-9f0e-b67a6600b012.png)

**Comment by jayarc** [comment]
At first I was using a PPA .deb package to install Vertex on 16.04, that looked like what you are seeing and so did the first try with compilation for me. What ended up solving this problem for me was to clone the repository from github on my local machine and follow the README installation guide BUT when you ./autogen.sh..... make sure you add  --with-gnome=<version>. Version in my case was "3.18". After this command I also issued the make command twice, seemed silly but somebody on some thread elsewhere said it may work, and the combination of the version setting and that tidbit got me going. Good luck!

**Comment by nihild3v** [comment]
Thanks for help, it works. I did the same process with ceti-2-theme but it fails. -with-gnome=3.20 generate an error
