### ISSUE TITLE
Consider doing a new release

### ISSUE THREAD

**Issue by EvaSDK** [horst3180/vertex-theme#228]
Last release/tag dates back in march, there has been quite a few fixes since then and it would be nice to have them released.

**Comment by philb61** [comment]
It may be time now, as the outlines seem broken in the newly released Ubuntu 16.10 (yakketty yak)

**Comment by almereyda** [comment]
Also for me on Fedora 24, I had to build it myself to get gnome-shell support.

**Comment by EvaSDK** [comment]
I see there is a new release now: https://github.com/horst3180/vertex-theme/tree/20170128

**Comment by echuber2** [comment]
But there are still many outstanding pull requests. It seems someone proposed maintaining a fork of the theme to keep it alive.

**Comment by EvaSDK** [comment]
Well this particular issue is resolved but I would sure be interested if there was an active fork.
