### ISSUE TITLE
Thunderbird: dark outline around toolbar buttons

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#28]
As far as I can see Vertex theme does not have dark (almost black) outline around toolbar buttons in other apps, but this outline used in userCrome.css for Thunderbird seems to pose problems in some buttons with a dropdown list like  Get New Messages, Forward, Mark, etc. Usually the dark outline is narrower that the button area, left edge of the arrow button doesn't show the outline, etc.

**Comment by horst3180** [comment]
Sorry, I had to drop the thunderbird theme. It's too much work to maintain. See 0caec039e0e4e23a1181e19ac9cabb6b63654ea5

**Comment by Sadi58** [comment]
I understand. Anyway thanks a lot for all your work on this to date.
It's really hard to achieve system-wide consistency with dark themes :\)
