### ISSUE TITLE
Non-CSD window decorations are too thin

### ISSUE THREAD

**Issue by pulb** [horst3180/Vertex-theme#30]
Compared to original Adwaita non-headerbar window decorations, Vertex non-headerbar window decorations are a little bit too thin and appear "squeezed". Please see the screenshots below which illustrates the issue.

![comparision1](https://cloud.githubusercontent.com/assets/827576/5207522/5029a390-75ab-11e4-926a-1197118fbb3f.png)
![comparision2](https://cloud.githubusercontent.com/assets/827576/5207524/512176ba-75ab-11e4-93be-c88253212f9c.png)

**Comment by pulb** [comment]
This doesn't seem to work in GNOME 3.16. Any ideas?

**Comment by horst3180** [comment]
You could create ~/.config/gtk-3.0/gtk.css with the following content

    .header-bar.default-decoration {
        padding-top: 5px;
        padding-bottom: 5px;
    }

    .header-bar.default-decoration .button.titlebutton {
        padding-top: 2px;
        padding-bottom: 2px;
    }

You can increase or decrease the padding values as you wish. After you saved the file you have to restart gnome-shell or log out and log back in again.

**Comment by pulb** [comment]
Awesome, looks fantastic! Many many thanks :-)
