### ISSUE TITLE
Request: add a highlight for drag targets in sidebars/treeviews

### ISSUE THREAD

**Issue by xcvfxq** [horst3180/Vertex-theme#35]
It would be nice if Vertex gave some indication as to which item in a sidebar or tree view was active when dragging over them. For example, here is how it looks in the current version of Adwaita:

![Imgur](http://i.imgur.com/dJWzimQ.png)

This makes it clear that releasing the drag here will hit the 'media' folder. Thanks for your consideration, and a great theme.

**Comment by horst3180** [comment]
It should be fixed now.
