### ISSUE TITLE
Gvim icon size in right mouse button menu.

### ISSUE THREAD

**Issue by manoevis** [horst3180/Vertex-theme#36]
![gvim](https://cloud.githubusercontent.com/assets/5586135/5566444/b2d69cde-8f30-11e4-9790-955424304791.png)

**Comment by horst3180** [comment]
Does this happen only with this theme? Looks like an issue with the icon theme to me.

**Comment by manoevis** [comment]
Yep, this is GTK bug, sorry for disturb.
"A workaround is to install a GNOME icon theme that includes its own vim 
icon (for example "gnome-colors-common") and select that icon theme in 
the GNOME Tweak Tool.  gnome-colors-common installs a bunch of fixed 
size vim.png icons and a scalable vim.svg (with a size of 48x48 pixels)." [ https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765069 ]
