### ISSUE TITLE
Request: create Ubuntu Software Center dark theme

### ISSUE THREAD

**Issue by manoevis** [horst3180/Vertex-theme#37]
f.e.: http://killhellokitty.deviantart.com/art/Dorian-Theme-353532019 < under Ubuntu Software Center section.

**Comment by manoevis** [comment]
I use the settings  from dorian theme, and looks nice, more native (except front-page which looks kinda ugly, but..)

**Comment by horst3180** [comment]
I added a fix for this now. This probably needs some testing, but everything should be readable now.
I agree about the frontpage, it's very ugly but unfortunately it can't be changed with this file. Maybe there's another .css file for this. For now this should do it, though.
