### ISSUE TITLE
Top panel color should be more consistent with the rest of the theme.

### ISSUE THREAD

**Issue by pradyun** [horst3180/Vertex-theme#38]
Firstly, AWESOME THEME!! Great job! :+1:

The only thing in this theme that I've found to be weird/inconsistent is the styling of the top panel in the shell theme. If it is coloured more like the dash, then IMO, the theme looks more consistent. 

I think a simple change in `Vertex-Gnome-Shell/gnome-shell/panel.svg`, replacing `#000000` and `#0c0c0c` with `#28292B` and `#3E4042` respectively and tweaking the transparency a bit should be enough...
A small drop shadow with that would be awesome!

PS: I fiddled with `panel.svg` before opening this issue. So I make those suggestions based on the little knowledge gained in the process... :innocent:

**Comment by horst3180** [comment]
It's better with the new gnome-shell theme, I think. I want it darker than the window headers for contrast. A drop shadow overlaps maximized windows and I don't like that.
