### ISSUE TITLE
metacity-theme-3.xml name field in theme variants

### ISSUE THREAD

**Issue by korrode** [horst3180/Vertex-theme#39]
Hi horst3180, the name field in metacity-theme-3.xml for some of the Vertex variants isn't set correctly, it's set only to "Vertex", rather than the variant name ("Vertex-Light" for example). metacity-theme-1.xml and metacity-theme-2.xml files are correct, only metacity-theme-3.xml files have the issue.

**Comment by horst3180** [comment]
Does this cause any problems?
Technically the metacity-3 themes are the same for all variants, because they adapt to colors set in the gtk3 theme. I thought I could leave it as a single file, to make things simpler.

**Comment by korrode** [comment]
Well i noticed Vertex listed multiple times in my Compiz GWD theme selector:
http://www.paradoxcomputers.com.au/images/vertex-listed-multiple.jpg

I guess it could be argued that it's on me to remove duplicates before displaying the list... but the list isn't 'incorrect' per se, there *are* multiple metacity themes called simply "Vertex" on the system...

**Comment by horst3180** [comment]
Yeah that's a bit ugly. I'll name the metacity themes differently.

**Comment by horst3180** [comment]
I haven't tested it, but it should be fixed now with this commit bcbfbcbf0b786ec126e5734a77e6987cf3c8e6e5
