### ISSUE TITLE
[xfce] system monitor bars broken

### ISSUE THREAD

**Issue by bjo81** [horst3180/Vertex-theme#40]
In my xfce toolbar, I have running the system monitor plugin (cpu, mem, swap) with white bars. When using the vertex theme, the bars are just empty.
![bildschirmfoto - 06 01 2015 - 00 12 25](https://cloud.githubusercontent.com/assets/1674578/5621823/7661a7d4-953a-11e4-8748-3a6dc4b47b4b.png) (between cputemp and the networkinterfaces)

**Comment by horst3180** [comment]
Thanks for reporting. I'll have a look at this.

**Comment by horst3180** [comment]
This should be fixed now. See 4c05de4593f5a5e298d3b43471ba77ed95d0300e
