### ISSUE TITLE
Not an issue, just need some help

### ISSUE THREAD

**Issue by PythonProof** [horst3180/Vertex-theme#41]
Hello, Mr. horst!
Is it possible for you to explain how to make bluish(whatever color) border around focused window?
I have tried to edit metacity-theme-3.xml without any result:(
I use cinnamon with maximus extension and tiling and it is must have feature for me.
Sorry for bad english.

**Comment by horst3180** [comment]
Hi, do you mean something like this?
![bildschirmfoto von 2015-01-07 22 15 22](https://cloud.githubusercontent.com/assets/8473629/5653503/16d718d0-96bb-11e4-97ad-0998a5bbd665.png)

You can find the .xml file here: http://pastebin.com/djiYhJtu

**Comment by PythonProof** [comment]
Yes. It works good enough without cinnamon maximus extention(remove titlebar from maximized and tiled windows), just doesnt make bluish border around tiled halftop and halfbottom windows. But as i know gnome doesnt have this tile possibility, and has only left and right. And this is gnome theme, so works perfectly. + works for tiled bottom-right tile, top-left tile etc, that seems strange.
But with maximus extention when a windows tiled seems like they transform into some different window type or so, and it still doesn't work:( 

Thanks for your time, answer and xml file. I will try to figure out where is the problem by myself.
