### ISSUE TITLE
Thunderbird (addon Lightning) calendar on left panel not readeable in dark theme

### ISSUE THREAD

**Issue by vantu5z** [horst3180/Vertex-theme#43]
Concretely not visible week days and controls items:
![2015-01-12 12 46 08](https://cloud.githubusercontent.com/assets/8698003/5701262/bb98faf4-9a59-11e4-9201-53cc7188d893.png)

**Comment by vantu5z** [comment]
I found that this file contain theme colors for calendar /home/user/.thunderbird/1g1nzuwh.default/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}/chrome/skin/linux/calendar/widgets/minimonth.css

**Comment by ThePhoenixBird** [comment]
In Thunderbird, go to Edit > Preferences > Calendar (created by addon Lightning) > General  and check (x) Optimize Colors for accessibility

**Comment by vantu5z** [comment]
Greate! Thanks!
