### ISSUE TITLE
Request: Plank theme

### ISSUE THREAD

**Issue by Zachs-Kappler** [horst3180/Vertex-theme#45]
I would like a theme for Plank, a basic themable dock used in Elementary OS.

**Comment by mephux** [comment]
@Zachs-Kappler I found that the http://me4oslav.deviantart.com/art/Numix-theme-for-Plank-393957556 theme goes well with Vertex.

**Comment by horst3180** [comment]
I think it would be easy to make a Vertex theme for Plank, probably using the same gradient as the dash in the gnome-shell theme, but it's not a top priority for me with gnome 3.16 being released this week. So if anyone wants to step in, feel free to do so.

**Comment by horst3180** [comment]
Done. See 93461d063b32a7754d43ca012f77af6f4bc40932 for details.
