### ISSUE TITLE
Rightclick menu crashes rhythmbox

### ISSUE THREAD

**Issue by aquatix** [horst3180/Vertex-theme#46]
I'm on Ubuntu Gnome 14.10 with the ppa's so I'm running Gnome 3.14.

The theme looks great, but when I select some tracks in rhythmbox and rightclick to get the menu to add them to the queue, rhythmbox segfaults:

sys:1: Warning: invalid uninstantiatable type '<invalid>' in cast to 'GMenuModel'
g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Segmentation fault (core dumped)

This doesn't happen with other themes.

**Comment by vantu5z** [comment]
I use Arch with gnome 3.14, rhythmbox 3.1-2.
And can't reproduce the issue.
Wich PPA do you use and what version of rhythmbox?

**Comment by aquatix** [comment]
These two ppa's:
https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3
https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging

I have Rhythmbox 3.0.3, which might be an issue too. Going to upgrade to the 3.1.x series now from add-apt-repository ppa:fossfreedom/rhythmbox and will report back.

**Comment by aquatix** [comment]
Sooo... colour me purple. The 3.0.3 version from those ppa's had the problem, but the more modern 3.1 I now have apparently has some fixes for Gnome 3.14. It works just fine.

Odd, but it seems that if you run a correct 3.14 stack, there's no bug :)

**Comment by horst3180** [comment]
Ok, I think this is solved, then.

**Comment by aquatix** [comment]
Yep, sorry for the noise. Thanks for the great theme!

**Comment by ikeydoherty** [comment]
For the sake of confirmation we had this issue in Evolve OS, its resolved moving to 3.1 (regardless of theme for us.)
