### ISSUE TITLE
Mods for newer vesions of dash-to-dock

### ISSUE THREAD

**Issue by vltr** [horst3180/Vertex-theme#48]
Hey, @horst3180!

I made a fork of your theme, with a simple mod regarding the dock location since newer versions of dash-to-dock plugin now supports other locations other then the left of the screen.

I just made the mod for the bottom, rotating images, paddings and creating them with a ".bottom" class in front of the css definition (I didn't changed gnome-shell-no-crash.css). Other sides, like right or top I didn't made it either because I don't know if you'll find it an acceptable pull request.

If so, please, let me know :)

My repository, with this simple mod: https://github.com/vltr/Vertex-theme

Here a screenshot of my dash-to-dock extension with Vertex modded :)

![screenshot from 2015-01-22 13 45 01](https://cloud.githubusercontent.com/assets/1540275/5858962/0f1e3752-a23e-11e4-91fb-26d506805819.png)

Best regards,
Richard.

**Comment by horst3180** [comment]
Thanks! I didn't notice this new feature until now. The modifications are looking good, so a pull request would be nice :)

**Comment by vltr** [comment]
thanks @horst3180! i'm glad you like it. for sure i'll make a pull request, i just have one question: since one of the "jobs" is to rotate some images, would you like to have them by hand (like i did today: open inkscape, rotated objects, etc) or a script that generates from a source (let's say, left) ?

best regards,
richard.

**Comment by horst3180** [comment]
I think it's okay to rotate them manually.
