### ISSUE TITLE
XUL and Qt problems

### ISSUE THREAD

**Issue by vltr** [horst3180/Vertex-theme#5]
hello @horst3180!

as I have mentioned at deviantart, here are some problems I have found on applications based on Qt or XUL.

-------------------------------

*XUL*: basically, the most annoying of it is the progress bar (when indeterminate - loading, it overflow the rounded borders):

![xul-stuff_01](https://cloud.githubusercontent.com/assets/1540275/4355946/2eaca59a-4253-11e4-8053-83982505ba08.png)
![xul-stuff_02](https://cloud.githubusercontent.com/assets/1540275/4355947/2eb2a076-4253-11e4-8746-d21608e4ef22.png)
![xul-stuff_03](https://cloud.githubusercontent.com/assets/1540275/4355948/2eb42d9c-4253-11e4-8aca-932c80cdb239.png)

--------------------------------

*Qt scrollbars*: they don't use the whole scroll area. It may be the same problem because it uses GTK2 as well (AFAIK). One example is Skype, which renders the scrollbar like this, when: 

![skype_01](https://cloud.githubusercontent.com/assets/1540275/4355943/26eb762e-4253-11e4-9132-1d8d1a3f302a.png)
![skype_02](https://cloud.githubusercontent.com/assets/1540275/4355942/26df5f42-4253-11e4-946d-28c90284f313.png)

**Comment by horst3180** [comment]
I'll close this now. Those are bugs in the Gtk 2 engine of qt and XUL apps and I can't fix them without breaking the theme for native Gtk 2 apps.

**Comment by vltr** [comment]
yeah, out of our reach, unfortunatelly.
