### ISSUE TITLE
Nautilus close button is wrong

### ISSUE THREAD

**Issue by EvanWashkow** [horst3180/Vertex-theme#51]
For all theme variants (Vertex, Vertex-Light, and Vertex-Dark), Nautilus' close button still remains a "X" instead of the theme's "O" close button.

Ubuntu Gnome 14.10
Gnome 3.12
I updated my master branch and built the theme on 2015-01-29

![screenshot from 2015-01-29 21 13 32](https://cloud.githubusercontent.com/assets/2553816/5971493/cd6bedae-a7fb-11e4-97bc-0fc5d2dcadd0.png)

**Comment by horst3180** [comment]
Hm, that's strange. Maybe nautilus doesn't load the theme properly. Close all nautilus windows and execute 

    killall nautilus

and start nautilus again and see if it's fixed.
Also try to enable all window buttons ( minimize, maximize, close ) with

    gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DecorationLayout': <':minimize,maximize,close'>}"

To revert back to a single close button, do

    gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DecorationLayout': <':close'>}"

Maybe this makes a difference.
