### ISSUE TITLE
Comboboxes and checkboxes on Firefox 35 using Vertex Dark

### ISSUE THREAD

**Issue by lasombra** [horst3180/Vertex-theme#54]
Hi,

It seems the Vertex Dark doesn't render properly on Firefox 35 under Gnome 3.14 using Vertex Dark as well.

![vertex_dark_ff35](https://cloud.githubusercontent.com/assets/347538/6246889/b519dd0a-b765-11e4-808d-35a9483af649.png)

**Comment by horst3180** [comment]
Yes, I am aware of this. Unfortunately this seems to be the only way to make all text entries readable. I have to reset the entry styles, so they don't get overwritten by the gtk2 theme. If I don't do this you would see some entries with dark background and black text (or light entries with white text), which basically makes them unusable.

See here the youtube searchbar for example
![bildschirmfoto von 2015-02-19 13 07 58](https://cloud.githubusercontent.com/assets/8473629/6266338/94be8726-b838-11e4-8995-c671db143600.png)
