### ISSUE TITLE
Libreoffice 4.4 Text foreground and background color dropdown not working

### ISSUE THREAD

**Issue by renatofdds** [horst3180/Vertex-theme#55]
The dropdowns for text foreground and background color on any Libreoffice 4.4.0.3 app are not being displayed. When you click on them nothing shows up.

**Comment by horst3180** [comment]
I'll have a look at this.

**Comment by horst3180** [comment]
Do you mean these? They seem to work fine for me with 4.4.1.2
![dropdown](https://cloud.githubusercontent.com/assets/8473629/6536594/229d85a2-c44f-11e4-94e6-8f348cc88b76.png)

**Comment by renatofdds** [comment]
Yes, these. They don't work for me. I'm using the darkest variant and also 4.4.1.2.

**Comment by a123b123c123** [comment]
They do not for me, too! A short flickering and then they disappear ..
I use FVWM as a WM but with LO 4.3 no problem was observed. Only now with the 4.4.x releases.
Interestingly the drop-downs for the frame settings are working well.

**Comment by horst3180** [comment]
Does it work with Adwaita?

**Comment by horst3180** [comment]
I just tested this under FVWM. The popup doesn't work indeed, but it's not theme related for me. It doesn't work with any of the themes I have installed. I'm pretty sure this is a bug in Libreoffice.
