### ISSUE TITLE
MPRIS Controls not show on elementary OS Freya

### ISSUE THREAD

**Issue by varlesh** [horst3180/Vertex-theme#56]
Vertex Dark 3.14
elementary OS Freya
Audacious 3.5
![23-02-2015 12 15 13](https://cloud.githubusercontent.com/assets/8083855/6325247/b6e4e816-bb55-11e4-91a2-a031d350f0a7.png)

**Comment by varlesh** [comment]
Install git version. MPRIS working, but white buttons :(
![23-02-2015 12 34 08](https://cloud.githubusercontent.com/assets/8083855/6325416/500325a6-bb58-11e4-912a-050e71028a67.png)

**Comment by horst3180** [comment]
This is a bug in the indicator-sound package, so there's nothing I can do about it. It is fixed in a newer version, but that hasn't landed in Freya yet.
