### ISSUE TITLE
GTK3 button background black on panels

### ISSUE THREAD

**Issue by jgeboski** [horst3180/Vertex-theme#57]
It seems that when GTK3 buttons are used on a panel, their background is just black.  I am using the GTK2 based xfce4-panel with the GTK3 based xfce4-pulseaudio-plugin.

![theme-error](https://cloud.githubusercontent.com/assets/615378/6532149/67a00c80-c40c-11e4-88be-ef5445ee1294.png)

![theme-error-hover](https://cloud.githubusercontent.com/assets/615378/6534635/f340f59c-c40c-11e4-8668-635ee9556a1e.png)

Versions:
- gtk+-2.24.26
- gtk+-3.14.9
- xfce4-panel-4.11.1
- xfce4-pulseaudio-plugin-0.2.0

**Comment by horst3180** [comment]
I will have a look at this when Xfce 4.12 leaves testing in Arch. Right now it seems that I can't compile the pulseaudio plugin without Xfce 4.11 or higher and I don't want to fiddle around with unstable packages.

**Comment by horst3180** [comment]
Ok, I think it is fixed now in master.

**Comment by jgeboski** [comment]
So it certainly has the correct background color now!  I was just wondering if there is any reason there is no opacity/alpha being applied to the buttons now.  Is this an issue with the theme or the application?

![theme-error](https://cloud.githubusercontent.com/assets/615378/6547624/6ebbe982-c5b3-11e4-9686-97a485cbc449.png)

**Comment by horst3180** [comment]
I think it's the application's fault. The theme has no information about the opacity and the panel should take care of that. Maybe it's because the panel is still gtk2 and the applet is gtk3.
The whole panel styling in xfce is a giant mess and it's almost impossible to make it look nice. Including gtk3 applets just makes it worse.

**Comment by jgeboski** [comment]
I just tested with the Adwaita theme, and it appears to work fine.  Maybe it is actually something with the theme?

![adwaita-alpha](https://cloud.githubusercontent.com/assets/615378/6561467/e18b313e-c667-11e4-986a-8a3afac849cc.png)

**Comment by horst3180** [comment]
That may be the case, then. I will try to find the problem.

**Comment by horst3180** [comment]
I think it's fixed now. I accidentally set the background color on the button, not on the panel.

**Comment by jgeboski** [comment]
I can confirm this has been resolved as of 84336b3.
