### ISSUE TITLE
GTK2 button oversized on panels

### ISSUE THREAD

**Issue by jgeboski** [horst3180/Vertex-theme#60]
GTK2 based panel buttons, in this case xfce4-panel, appear to be over sized.  This seems to only occur with GTK2 based applications.

Issue present with xfce4-power-manager:
![issue-1](https://cloud.githubusercontent.com/assets/615378/6611252/9907985a-c840-11e4-847f-58821c9dcabe.png) ![issue-2](https://cloud.githubusercontent.com/assets/615378/6611251/99063d5c-c840-11e4-9485-e0253ba98bba.png)

Issue not present with Adwaita theme:
![issue-3](https://cloud.githubusercontent.com/assets/615378/6611249/9904c3dc-c840-11e4-981c-4505dcd4711f.png) ![issue-4](https://cloud.githubusercontent.com/assets/615378/6611250/99057b6a-c840-11e4-9d15-8073fdf84656.png)

Versions:
- gtk+-2.24.26
- gtk+-3.14.9
- xfce4-panel-4.11.1
- xfce4-power-manager-1.4.3
- xfce4-pulseaudio-plugin-0.2.0

**Comment by horst3180** [comment]
I'm working on this. The problem is that when I fix it with xfce-panel, mate-panel gets borked, so I have to make two different panel styles...

**Comment by horst3180** [comment]
I think it is fixed with d6b2ef03169847cac0c448f2baa9fc1843895aee. I trashed the entire panel styling. Now everything is drawn with the murrine engine and not with pixmap, which seems to work better.

**Comment by jgeboski** [comment]
I can confirm this resolves the issue.  Thanks!

**Comment by jgeboski** [comment]
It is also worth noting that not only does this fix the issue, but it looks significantly better, and window alerts work now.

**Comment by horst3180** [comment]
Thanks, I'm glad it finally works. It was a nightmare to get this right :)
Btw. now that I see your name, it was you who asked me on irc about migrating to a proper build system, right?

**Comment by jgeboski** [comment]
Yes, would you have any interest in that?  I would be will to do the work.

**Comment by horst3180** [comment]
Definitely, if your are willing to do that, that would be awesome.

**Comment by jgeboski** [comment]
Cool, I'll poke away at it in my free time, and get you a pull request in the near future.

**Comment by horst3180** [comment]
Nice! Are you planning to use autotools or something different?

**Comment by jgeboski** [comment]
Autotools, unless there is an objection.  That will keep consistent with the other GNOME things, which are all autotools based.

**Comment by horst3180** [comment]
Autotools would be my choice, too. I'm no expert, but I think it should be possible to conditionally build the theme depending on the installed gtk3 version. That would be pretty neat.

**Comment by jgeboski** [comment]
Yup, already in the plans! :)

**Comment by horst3180** [comment]
Sweet. When that's working I could look into some automatic package building for different distributions like open build service.
