### ISSUE TITLE
GTK2 horizontal scroll bars broken on hover

### ISSUE THREAD

**Issue by jgeboski** [horst3180/Vertex-theme#61]
The horizontal scroll bar breaks when it is hovered within a GTK2 based application.  This only appears to happen with GTK2 based applications, and does not appear to affect GTK3.  This also only happens with the vertex-dark theme variant.

![issue-1](https://cloud.githubusercontent.com/assets/615378/6611682/f7c7e2be-c845-11e4-848f-d00da00b57a5.png)

**Comment by horst3180** [comment]
Should be fixed now.

**Comment by jgeboski** [comment]
Kudos!
