### ISSUE TITLE
Theme issue in Ubuntu Gnome 14.04

### ISSUE THREAD

**Issue by nghitran** [horst3180/Vertex-theme#63]
Hi, I tried 2 versions: one from Deviant Art and one built from git, but they both breaks when I choose the WM preference to Vertex, please view the screenshot in the link below for more information:

http://cl.ly/image/462E3g1q0E2u

Here's the output I got from starting gedit in terminal:

>Gtk-WARNING **: Theme parsing error: gtk-widgets.css:997:2: Missing name of pseudo-class

I really love your theme, hope you can figure out the issue soon.

**Comment by horst3180** [comment]
I have to spin up a vm with 14.04 to test. In the meantime please make sure you installed the theme to /usr/share/themes and followed the installation instructions in the README.

**Comment by horst3180** [comment]
I can't confirm this bug, so the problem is on your end. The parsing error is due to a Gtk 3.12 feature that isn't recognized by Gtk 3.10 in Ubuntu but it shouldn't cause any problems. The only advice I can give you is to read the installation instructions carefully.

**Comment by nghitran** [comment]
Thanks for your quick reply, I installed it in /usr/share/themes/ as your suggestion and it works perfect now. Previously, I installed it in ~/.local/share/themes/ (I prefer installing theme for local use) maybe it didn't work because I missed linking the ~/.themes to ~/.local/share/themes.
Anyway, it worked! Thanks for your hard work on this beautiful theme.
