### ISSUE TITLE
Is there an easy way to install the theme in ubuntu...

### ISSUE THREAD

**Issue by PerfectCarl** [horst3180/Vertex-theme#67]
... and be kept up to date?

I'm thinking about a deb file or a ppa.

**Comment by PerfectCarl** [comment]
Here's what I did on elementary freya/ubuntu 14.04: 
```
git clone https://github.com/horst3180/Vertex-theme.git
sudo cp -R Vertex-theme/Gnome-3.14/Vertex /usr/share/themes/
sudo chmod -R 755 /usr/share/themes/Vertex

sudo cp -R Vertex-theme/Gnome-3.14/Vertex-Dark /usr/share/themes/
sudo chmod -R 755 /usr/share/themes/Vertex-Dark

sudo cp -R Vertex-theme/Gnome-3.14/Vertex-Light /usr/share/themes/
sudo chmod -R 755 /usr/share/themes/Vertex-Light

```
And to set up the theme, run: 
```
gsettings set org.gnome.desktop.interface gtk-theme "Vertex"
gsettings set org.gnome.desktop.wm.preferences theme "Vertex"
```
or 
```
gsettings set org.gnome.desktop.interface gtk-theme "Vertex-Light"
gsettings set org.gnome.desktop.wm.preferences theme "Vertex-Light"
```
or
```
gsettings set org.gnome.desktop.interface gtk-theme "Vertex-Dark"
gsettings set org.gnome.desktop.wm.preferences theme "Vertex-Dark"
```

**Comment by horst3180** [comment]
There are no packages for distributions available yet (except for Arch), but I'm working on this. What is the question in your second post? When you install the theme from git you need to run

    cd Vertex-theme
    chmod +x build.sh
    ./build.sh

after the git clone command.

**Comment by Sadi58** [comment]
In the meantime I locally store it with these commands:
```
mkdir -p ~/.local/share/themes/Vertex
git clone https://github.com/horst3180/Vertex-theme.git '~/.local/share/git/Vertex'
cd '~/.local/share/git/Vertex' && git pull
```
After this, symlinking (instead of copying) appropriate files and folders to a theme folder like '~/.local/share/themes/Vertex' and then using the command below (e.g. cronjob or startup command) helps me keep  up to date:
```
cd '~/.local/share/git/Vertex' && git pull
```
