### ISSUE TITLE
alt metacity

### ISSUE THREAD

**Issue by vltr** [horst3180/Vertex-theme#68]
oh man, gnome 3.16 is great and the upgraded theme still rocks. but, i'm keen to see the alt metacity theme working again. is it possible? need some help?

**Comment by horst3180** [comment]
It doesn't seem that it's possible anymore with the new css decorations. In theory it could work, but in order to hide the title on maximized windows I have to set the font-size to 0. Unfortunately the font-size seems to be controlled via some gsetting and not by the css.

**Comment by vltr** [comment]
damn. dconf-editor seems to have vanished (in my computer, at least). but with a <code>dconf dump /</code> i can see this:

<pre>
[org/gnome/desktop/wm/preferences]
button-layout='close,maximize,minimize:'
theme='Vertex-Dark'
num-workspaces=1
titlebar-font='San Francisco Display Medium 12'
</pre>

setting it to 0 <code>gsettings set org.gnome.desktop.wm.preferences titlebar-font "San Francisco Display Medium 0"</code> gives me this:

![image](https://cloud.githubusercontent.com/assets/1540275/6851208/5a09c628-d3bc-11e4-892a-a740e82d7177.png)

what else can we do to "test" this approach? :)

**Comment by horst3180** [comment]
I'm afraid we can't do anything. The font size has to be set to zero for maximized windows only, but the gsetting only allows to set it to the same size for all windows and overrides the theme settings no matter what.
dconf-editor has vanished from my system aswell, maybe it got removed?

**Comment by vltr** [comment]
yeah, well, i can live without window titles and buttons, because i
basically use the keyboard :) but that would be a plus for me. where i can
find the window css in gnome 3.16? i'm kind of lost here.

about dconf-editor, yeah, pacman says it is on the dconf package, but it
isn't. i think it was removed in upstream or testing or something.

**Comment by horst3180** [comment]
Another thing I just realized: the minimum size of the decorations is 16px now because of the icons, so even if the font size is zero the window decorations wouldn't get a lot smaller.

If you want to remove all padding you have to edit _common.scss line 1216-1217, set the padding to 0 and execute parse-sass.sh

    diff --git Vertex-gtk/gtk-3.0/_common.scss Vertex-gtk/gtk-3.0/_common.scss
    index 56250a0..3b61a0c 100644
    --- Vertex-gtk/gtk-3.0/_common.scss
    +++ Vertex-gtk/gtk-3.0/_common.scss
    @@ -1213,8 +1213,8 @@ GtkComboBox.combobox-entry .button:only-child,
         border-radius: 0; // squared corners when the window is max'd or tiled
       }
       &.default-decoration {
    -    padding-top: 3px;      // less padding for ssd
    -    padding-bottom: 3px;  //
    +    padding-top: 0px;      // less padding for ssd
    +    padding-bottom: 0px;  //
         background-color: $metacity_bg_a;
         background-image: linear-gradient(to bottom,
                                      $metacity_bg_a,

It doesn't have much effect as you see here
![window](https://cloud.githubusercontent.com/assets/8473629/6852882/c596f7be-d3e7-11e4-9761-d14cd24ac368.png)

**Comment by vltr** [comment]
well, i removed the buttons also, so it is not perfect; but i think i can
live with that for now :)

**Comment by horst3180** [comment]
Ok, I assume I can close this.

**Comment by vltr** [comment]
Yes, of course. It was not even an issue, more like a doubt to me, but
since github doesn't provides a FAQ (yet) ... :)
Em 26/03/2015 15:16, "horst3180" <notifications@github.com> escreveu:

**Comment by horst3180** [comment]
Well, there's a wiki, but nobody seems to use it :)

**Comment by vltr** [comment]
good point. i feel like a fool now, lol
