### ISSUE TITLE
Vertex-Light Unity Launcher dark borders

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#70]
I don't know if it's intentional but I have a feeling that having a common "unity" sub-folder is causing  dark thick borders around Unity Launcher icons which don't seem to quite fit the Light version.
If it's intentional, could you please suggest a quick and easy way of increasing transparency of these borders so that they are so striking?

![vertex-light_unity-launcher-issue](https://cloud.githubusercontent.com/assets/6375934/6884799/c1e4dc56-d60a-11e4-9c2f-1f484ef35b0a.png)

**Comment by horst3180** [comment]
I don't find it unfitting tbh. I felt the icon background needed a bit more contrast to be visible on all backgrounds.
The images unity loads for these elements are launcher_icon_edge_54.svg and launcher_icon_edge_150.svg in the unity folder. You can make them more transparent with inkscape. In case you're not familiar with inkscape, just open the .svg files with inkscape, press ctrl+a to select all objects, then press ctrl+shift+f to open the fill and stroke dialog where you can adjust the opacity.

**Comment by Sadi58** [comment]
OK, thanks...
