### ISSUE TITLE
Vertex-Light: a couple of suggestions

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#71]
I've just moved from Vertex to Vertex-Light due to many compatibility issues in apps like Thunderbird.

If I may I'd like to ask if you can consider making this great theme a little "less white", so to speak, or a tiny little bit closer to the silver grey color of similar themes like Zukiwo and Greybird?
Or suggest a quick and simple way of implementing such a tweak?
For example, I've changed "theme_bg_color" in "./gtk-3.0/gtk.css" from "#F5F5F7" to "#E5E7E9", and "bg_color" in "./gtk-2.0/gtkrc" from "#F3F3F5" to "#E5E7E9" as well as decreasing brightness of "./gtk-2.0/Toolbar/inline-toolbar.png" and "./gtk-2.0/Toolbar/toolbar.png" by 14 points.
But it seems there are a few other changes that I need to make to complete this adjustment...
What made to think like that: 1) When I click on Thunderbird title bar (to see the menus under Ubuntu) a whitish line appear between title/menu bar and tab container. 2) I see the the same toolbar bgcolor in Compose window. But when I use Greybird theme's gtkrc (with necessary color code changes) this problem disappears (however Vertex-Light gtk-2.0 theme is far better in all other aspects, including buttons, boxes, etc.) 

Secondly, I have also a similar suggestion for Nautilus sidebar, which is hardly discernible from the main window.
For example, I've copied and pasted the Nautilus Sidebar section from the main Vertex theme, changing the background color to "#E5E7E9" also making a couple of other necessary changes regarding color definitions.

I'm sure you can find much better color codes than me ;-)
Thank you so much for this set of superb themes.
PS: As a heavy Thunderbird user, the two minor issues put me off from using my basic tweaks though.

**Comment by horst3180** [comment]
Sorry for the late answer, I was quite busy with other things (new build system, setting up package repositories, fixing critical bugs, etc.).
I think I will keep the colors as they are, but you can ask me if you need help with your modifications.
It seems that you've made the most important changes already. The gtk2 uses a lot of images for drawing certain elements. If you change the color just in the gtkrc those wont change. So you have to look for images that still have the lighter color and modify them.

**Comment by Sadi58** [comment]
Thanks a lot for making this great theme even better with so much renewed effort as seen in its new setup.
I think I'll go with your decision about the main background color of the Light version, partly because it's too complicated for me to produce a consistent change.
However, I would appreciate very much if you can let me know how I can change the Nautilus Sidebar, for instance to the same one as the toolbar.

**Comment by horst3180** [comment]
Thanks, you can create `~/.config/gtk-3.0/gtk.css` to override specific theme settings. To change the nautilus sidebar background you need to put this into the `gtk.css` file

    NautilusWindow .sidebar .view,
    NautilusWindow .sidebar {
      background-color: #EAEAED;
    }

After you saved the file you have to restart nautilus. Sometimes it keeps running in the background after you closed the window. In this case a `killall nautilus` shoud help.
You can tweak the color code as you like. If you want to use a different theme, you should rename the file or comment its content to prevent it from overriding the settings of the other theme.
The good thing about this is, that you won't have to change something if Vertex gets an update.

**Comment by Sadi58** [comment]
Thank you very much. This is a good idea to make customisations, which I wish I knew before ;-)

**Comment by horst3180** [comment]
Yes, it's very nice for small customizations, I only recently learned that this is possible.

**Comment by Sadi58** [comment]
I've found the color code `#EFEFF0` slightly closer and better matching to the toolbar above and also added these lines (borrowed from elsewhere) to draw a border on the right:
```
NautilusWindow > GtkGrid > .pane-separator,
NautilusWindow > GtkGrid > .pane-separator:hover {
    border-width: 0 1px 0 0;
    border-style: solid;
    border-color: shade(@theme_bg_color, 0.8);
}
```
But it seems a gradient background would please me much better.
I tried using `background-image: linear-gradient(to bottom, #f4f4f4, #e2e2e4);` from your `gtk-contained.css`, but then I've got button like shapes (gradient repeating) for each item.
Any idea to avoid this odd behaviour please?

**Comment by horst3180** [comment]
Hm, there should already be a border on the sidebar. Are you sure you are using the correct version of the theme?
I've tried before to draw a gradient on the sidebar, but it seems that it's not possible.

**Comment by Sadi58** [comment]
Sorry, yes, there's a border in deed; perhaps I couldn't see it after changing themes (without restarting Nautilus).
You're probably right about the gradient on sidebar.
I wonder if we could use an image file to create the same effect then?

**Comment by horst3180** [comment]
I think I have an idea with the gradient. I don't know if it will work, though

    NautilusWindow .sidebar .view {
      background-color: transparent;
    }

    NautilusWindow .sidebar {
      background-image: linear-gradient(to bottom, #f4f4f4, #e2e2e4);
    }

**Comment by Sadi58** [comment]
Yes, it works, thanks a lot!
Now it seems I need to tinker a bit more with this pair of codes to create a background similar to the toolbar.
