### ISSUE TITLE
Non-CSD windows don't have a "close" button

### ISSUE THREAD

**Issue by Weegee** [horst3180/Vertex-theme#73]
I'm running GNOME 3.16 on Arch Linux using the vertex-themes-git package (r452.20150329-1), and for some reason only applications which use client-side decorations (like gedit, Nautilus etc.) have a "close" button in the title bar on the right, non-csd applications don't. For example: 

![2015-03-29_17 23 03](https://cloud.githubusercontent.com/assets/748975/6886310/b7a3cf3a-d638-11e4-9eac-5f01241c013e.png)

I can still close the non-csd windows by clicking on the spot where the button is supposed to be however, it's just not visible.

**Comment by horst3180** [comment]
The aur package hasn't been updated to support Gnome 3.16 because that's still in testing and it would break the package for everyone who is not on testing.
Try changing _gnomever=3.14 to _gnomever=3.16 in the PKGBUILD to enabla 3.16 support.

**Comment by Weegee** [comment]
Whoops, I've overlooked that variable. Looks fine now, thanks!

**Comment by l3ZoOoZl** [comment]
Hi 
I using ubuntu 15.04 with gnome 3.16 and I have the same problem , and can't find "gnomever"
so how I can fix
