### ISSUE TITLE
Porting to Autotools

### ISSUE THREAD

**Issue by jgeboski** [horst3180/Vertex-theme#74]
As per the initial conversation in #60, it seems like a good idea to migrate the project autotools.  This issue is to track the progress with any questions which arise might during the process.

Key Goals:
  - Simplify the building and packaging process
  - Provide an interface which many packagers are familiar with
  - Allow the toggling of different theme features during build-time
  - Ease of install for end-users with automatic version detection

**Comment by jgeboski** [comment]
Questions:
  1. There are `gnome-shell`s for 3.16 and pre-3.16.  However, there are also `vertex-gtk`s for 3.10-3.12, 3.14, and 3.16.  What is the key difference between these?  I tried diffing the directories, but that was less than pretty.  Is there anyway to consolidate these?  (Maybe at least XFWM and Unity?)
  2. What is the relevance of `Vertex_alt_metacity`?

**Comment by horst3180** [comment]
Okay, let's see.

* The `gtk-2.0` and `gtk-2.0-dark` directories are identical for each `Vertex-gtk` directory , aswell as the `index.theme`, `index.theme-light` and `index.theme-dark` files.

* I can backport the new window button hover states to the older versions which would make the `metacity-1`, `unity`, `xfwm4` and `xfwm-4-light` directories identical, too.

The only difference between the `Vertex-gtk` directories would then be the `gtk-3.0` directory. I can split up the `gtk-3.0` directory of the `Vertex-gtk-3.10-3.12` in two directories for each version.

That would allow for a nicer directory structure that would be something like

    .
    ├── 3.10
    │   └── gtk-3.0
    ├── 3.12
    │   └── gtk-3.0
    ├── 3.14
    │   └── gtk-3.0
    ├── 3.16
    │   └── gtk-3.0
    ├── common
    │   ├── gtk-2.0
    │   ├── gtk-2.0-dark
    │   ├── metacity-1
    │   ├── unity
    │   ├── xfwm4
    │   └── xfwm4-light
    ├── extra
    │   ├── Chrome
    │   ├── Firefox
    │   ├── Ubuntu-Software-Center
    │   └── Vertex_alt_metacity
    ├── Vertex-Cinnamon
    ├── Vertex-Gnome-Shell
    └── Vertex-Gnome-Shell-3.16

The Vertex_alt_metacity ist not very important. It just hides the buttons and title on maximized windows. It's only compatible with gnome 3.10-3.14 (not even with mate), so I'm not sure if we want it in the build.
The Firefox, Chrome and Ubuntu Software Center themes need to be excluded, too I would say. All the parts that require manual installation or are not wanted by everyone are included in the extra directory. People can still get them from git and install them if they want. Maybe a separate repository for this would be a good solution too.

**Comment by vltr** [comment]
+1 for autotools. @horst3180: I'm not a hardcore user of autotools, all I was doing is a bunch of bash scripts to install the theme basing on some simple questions prompts, like "would you like to install the firefox theme? [Y/n]". dead simple straightforward.

**Comment by jgeboski** [comment]
@horst3180 perfect!

**Comment by horst3180** [comment]
@jgeboski Good, I will get to work and create a branch with the proposed structure.
@vltr A separate script would work well for the Firefox and Ubuntu Software Center themes, I think. But I don't know if there's a way to install a Chrome theme this way.

**Comment by jgeboski** [comment]
@horst3180 Might be cleaner to migrate 3.??/gtk-3.0 to common gtk-3.0/3.???  That way we can just drop a Makefile.am in common.

**Comment by jgeboski** [comment]
@horst3180 I know one use to be able to install chrome extensions, but now they require you to pull everything through the store, so I don't know if it is still possible.  I'll look into it.

**Comment by vltr** [comment]
@horst3180 : being chrome or chromium in path, it's not hard to launch it with the crx. It's not completely automatic, because the user will have to accept it (as default behavior in chromium). Distro specific stuff might be a bit clumsy (st2 fix I can't even imagine where to start, lol), I have to download them and see what I can do :)

**Comment by horst3180** [comment]
@jgeboski Do you mean this

    common
    ├── gtk-2.0
    ├── gtk-2.0-dark
    ├── gtk-3.0
    │   ├── 3.10
    │   ├── 3.12
    │   ├── 3.14
    │   └── 3.16
    ├── metacity-1
    ├── unity
    ├── xfwm4
    └── xfwm4-light

**Comment by vltr** [comment]
@jgeboski : your work will be highly appreciated, since integrating it to package managers is much more simple than writing debs and rpms and etc.

**Comment by jgeboski** [comment]
@horst3180 Yup!

@vltr :)

**Comment by jgeboski** [comment]
@horst3180 it might also be easier if `Vertex-Gnome-Shell*` was moved to `common/gnome-shell/3.??`.  This was we can have a simple Makefile.am in gnome-shell.  That way you do not have to modify and copy Makefile.ams all over the place when you add a new version.

**Comment by horst3180** [comment]
Yes, that's a good idea.

**Comment by horst3180** [comment]
Ok, `autotools` branch is online. I moved the cinnamon theme to common too.

**Comment by jgeboski** [comment]
Kudos! This was the part tripping me up.  I'll get back to business.  I have two exams this week (university student), so my time is a little short.  I already have the core things setup, so hopefully I'll have this done soon.

**Comment by jgeboski** [comment]
I have completed a very rough initialization of autotools at [jgeboski/Vertex-theme](https://github.com/jgeboski/Vertex-theme/tree/autotools).  There is still very much to do.

**Comment by horst3180** [comment]
:+1:

**Comment by horst3180** [comment]
@jgeboski 
Here is some clarification with regard to https://github.com/horst3180/Vertex-theme/pull/88#issuecomment-92556240

https://github.com/horst3180/Vertex-theme/commit/4bff3669f3d2bafe46e286c6a06756131f551b77 shows how the build instructions should look like for Gnome 3.10 and 3.12. I know it's ugly, I just threw this together to show you.

**Comment by jgeboski** [comment]
Yeah, was going to do just that.

**Comment by jgeboski** [comment]
So, we can just use your patch, however, I was going to try and figure out something a little more elegant.  Something where, when you add a new version of GNOME, you do not have to edit `configure.ac`.

**Comment by horst3180** [comment]
@jgeboski I think I found a better way (2a96dfaa31629a0e7a5c684af84eafb4d4a1c094). I renamed and added a few files to make the directory structure of the 3.10 and 3.12 versions compatible with the build instructions for the newer versions.

**Comment by jgeboski** [comment]
Yeah, that's much better if that addresses the versioning.  Does this address everything?

**Comment by horst3180** [comment]
Yes, it builds for all versions now without changes to the build system.

**Comment by jgeboski** [comment]
Nice!

**Comment by horst3180** [comment]
I have a question, because I'm a noob when it comes to autotools.
Are you sure the automatic version detection works?

The `PKG_CHECK_VAR` macro called by `VERTEX_GNOME` executes 

    pkg-config --variable=version "gnome-desktop-3.0"

But there's no variable called `version` defined in the .pc file, so the command returns an empty string. Because of this `PKG_CHECK_VAR` always does this

    GNOME_VERSION=`ls -1 "$GNOMEDIR" | tail -1`]

Replacing the `PKG_CHECK_VAR` block with

    AC_REQUIRE([PKG_PROG_PKG_CONFIG])
    GNOME_VERSION=`$PKG_CONFIG --modversion gnome-desktop-3.0`

seems to work.

**Comment by jgeboski** [comment]
Fixed!  This got over looked.  I rebased my `autotools` branch, which resolves the issue, and pulls in your patch.

**Comment by horst3180** [comment]
Awesome! I think it's pretty much good to go now. I just need to update the Readme.

**Comment by horst3180** [comment]
Another small thing.
I noticed that Ubuntu 14.04 uses gtk 3.10 but only has gnome-desktop 3.8. I think it would be better to check the version of gtk+-3.0, since that is the part that really matters.

**Comment by jgeboski** [comment]
What are the required GTK versions for each internal GNOME version?

**Comment by horst3180** [comment]
Normally the gnome and gtk versions are identical (but Ubuntu has to be special, of course). The gtk version is more important for Vertex, since the gtk3 themes are written against those versions. So if we replace gnome-desktop-3.0 with gtk+-3.0 in the build system, everything should be fine.

**Comment by jgeboski** [comment]
There are three obvious routes:

1. Increment the version automatically in `vertex-gnome.m4`
2. Add `3.8` symbolic links in `gnome-shell` and `gtk-3.0`
3. Document usage of `--with-gnome=3.10`

Which would you prefer to do?

**Comment by horst3180** [comment]
I would just check the gtk+-3.0 version instead of gnome-desktop-3.0. The gnome-desktop version shouldn't matter for the theme at all.

**Comment by jgeboski** [comment]
Yes, however, we still need to address the versions with the sub directories.

**Comment by jgeboski** [comment]
Disregard my previous statement, I misread your message above.  Sorry!

**Comment by jgeboski** [comment]
Shall `vertex-gnome` be migrated to `vertex-gtk`, or stick the way it is?

**Comment by horst3180** [comment]
I think we can keep it how it is.

**Comment by jgeboski** [comment]
Fixed in `vertex-gnome.m4` and rebased.

**Comment by horst3180** [comment]
In common/makefile.am the command to copy the gnome-shell theme should be changed to

	cp -r -H $(srcdir)/gnome-shell/$(GNOME_VERSION) $(ithemedir)/gnome-shell

to follow the symlinks.

**Comment by jgeboski** [comment]
Whoops!  While I am it, it might be wise to add `-H` to any `cp` operation souring `$(GNOME_VERSION)` in `common/Makefile.am`?  This way, if links are needed down the road, no modifications will get in the way.

**Comment by horst3180** [comment]
Yes, that would be good.

**Comment by jgeboski** [comment]
Fixed and rebased.

**Comment by horst3180** [comment]
Perfect! I think everything works now. Thanks a lot for your work, it's so much better than before.

**Comment by jgeboski** [comment]
:)

**Comment by horst3180** [comment]
Again, awesome work, thanks :)
