### ISSUE TITLE
Vertex-Light: Nautilus Trash infobar bgcolor

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#75]
I think we need a darker bgcolor for Nautilus Trash infobar immediately below the toolbar. Perhaps a very light shadow of grayish blue or yellow?

![vertex-light_trash-issue](https://cloud.githubusercontent.com/assets/6375934/6892495/4c1529fe-d6cd-11e4-9bd2-8b002373a650.png)

**Comment by horst3180** [comment]
Right, that should be styled differently. Actually it works with newer nautilus versions, and I don't remember why I changed it for this version. I will try to get it right.

**Comment by horst3180** [comment]
Ok, I had a look at this...
The thing is that the infobar has the correct background color with upstream nautilus. The widget is a GtkInfoBar and has the .question class attached to it on an unpatched nautilus. Ubuntu patches some apps (including nautilus) quite heavily and for some reason the .question class got removed and this is why it looks bad.

Here is a comparison between nautilus 3.14.x on a standard Arch install and on a Ubuntu 15.04 install
![nautilus_upstream](https://cloud.githubusercontent.com/assets/8473629/6989678/fee7361e-da5e-11e4-82c8-f8e369550d96.png)
![nautilus_ubuntu](https://cloud.githubusercontent.com/assets/8473629/6989679/02679950-da5f-11e4-885b-6a4dd9fa531e.png)

I can't do anything about it, this is an Ubuntu bug.

**Comment by Sadi58** [comment]
I forgot to mention that I have this problem under Ubuntu 14.10 (Nautilus 3.10.1 which I guess corresponds to GTK 3.12?) which will be a thing of the past in 10 days or so anyway ;-)
Nevertheles, out of curiosity, I also looked at other themes and saw that this is indeed a problem in many others as well. But there also some who have managed to get a darker bgcolor for Trash (and possibly other) infobars, e.g. Mediterranean White and Medilight. Some others, however, chosen to resolve this problem by using a bottom border for the infobar.
I'll wait and see what I'll get under Ubuntu 15.04 in less than two weeks ;-)

**Comment by horst3180** [comment]
It seems that it will be still an issue in 15.04. I think I found the patch that breaks it http://bazaar.launchpad.net/~ubuntu-desktop/nautilus/ubuntu/view/head:/debian/patches/ubuntu_infobars_color.patch
I honestly don't know why they would do that, I mean it breaks with Ambiance and Radiance too. It seems they do that on purpose, though.
I think I could make a workaround for this in Vertex, now that I know what's going on.

**Comment by horst3180** [comment]
Commit 46dc474554908195f7446bf4b1bcb9ec4a90e046 should fix this.
