### ISSUE TITLE
Vertex-Light: GTK-2.0 tab title bgcolor?

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#76]
My favorite plain-text editor is KKEdit (mainly for its powerful macro support) which is - unfortunately - a GTK2 application unlike gedit. So I don't have those fancy tabs but instead I see an awkward bgcolor underneath the file name with the tab canvas (different color) surrounding it.
I wonder if we can get rid of this, say, by making this bgcolor the same as the tab canvas color below :\)
(I guess this is the last tiny bit to make this theme fully and 100% perfect :-)

![vertex-light gtk2-tab-bgcolor-issue](https://cloud.githubusercontent.com/assets/6375934/6892745/36be59f2-d6cf-11e4-99b8-57f8e96e7dd3.png)

**Comment by horst3180** [comment]
I've seen this bug with a lot of themes. I think it occurs with gtk2 themes using the pixmap engine. It's probably a bug in the gtk-qt engine which translates the gtk2 style to qt apps. I don't think there's anything I can do about it.

**Comment by Sadi58** [comment]
OK, thanks for the info...
