### ISSUE TITLE
thunderbird dropped?

### ISSUE THREAD

**Issue by vltr** [horst3180/Vertex-theme#77]
@horst3180, me again. was the thunderbird vertex theme dropped out?

**Comment by horst3180** [comment]
It has been dropped for now, yes. Maybe it will come back if someone wants to maintain it (me included). You can still get it from and older release.

**Comment by vltr** [comment]
yeah, i'm using it from an older release. I think the main problem here is that you completely rewrote vertex in sass, while firefox and thunderbird uses they're own css and probably a pain to rewrite in sass (without a skeleton or reference to use). chrome uses it's own format, so ... nevermind about it, so to speak. i'm not a huge fan os sass, but i'll look into it to see what can be achieved from there.

**Comment by horst3180** [comment]
The sass port is not the main reason I dropped it. I just don't want to work around all the thunderbird UI bugs with a crapton of unmaintainable css. Also a lot of extensions look bad with a custom userchrome, so it's really unpredictable and I can't keep track of all the extensions and make special cases for them.
With firefox it doesn't seem quite as bad, so I kept the firefox theme.

**Comment by vltr** [comment]
oh, right, there's the extension question also. i use vanilla thunderbird,
that's why it's not bad to me :) either way, i _think_ it is possible to
"circumvent" some of the problems by using sass to xul apps too.
