### ISSUE TITLE
LibreOffice Style and Font Name text issue

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#78]
I often see scrambled text in Style and Font Name boxes in LibreOffice 4.4.1.2 under Ubuntu 14.10 - tried all 3 variants of Vertex.
(Never mind the window control buttons - just experimenting ;-)
![lo style font issue](https://cloud.githubusercontent.com/assets/6375934/6924853/0f693956-d7e4-11e4-940f-15e0e281ad1f.png)

**Comment by horst3180** [comment]
Is there a reliable way to reproduce this error? I just tested and this didn't happen.

**Comment by Sadi58** [comment]
I think presence of several fonts in the document and a number clicks around the text might help to reproduce it.

**Comment by horst3180** [comment]
Hmm, I still haven't managed to reproduce this. Does this happen with the Adwaita theme too? It should be in the `gnome-themes-standard` package.

**Comment by Sadi58** [comment]
I think I've found something. I haven't got the gnome-themes-standard package installed as I don't use those theme at all. But when I installed the problem disappeared. I've also got a white background in those three boxes which were previously grey as seen in the screenshot.
I didn't know there was such a dependency...

**Comment by horst3180** [comment]
Ah, ok. The theme uses the Adwaita engine for some small things and `gnome-themes-standard` is mentioned as a requirement in the readme. However, that's quite easy to miss hence I plan to make distribution specific packages. That will greatly simplify the installation and update process.
I think this is solved, then.

**Comment by Sadi58** [comment]
Yes, sorry about this oversight :$
