### ISSUE TITLE
Gnome Clock Calendar Style

### ISSUE THREAD

**Issue by samueljun** [horst3180/Vertex-theme#79]
The bottom border of the calendar month overlaps with the last row of week dates. See below:

![ufvd3ak](https://cloud.githubusercontent.com/assets/1808588/6937109/be246af0-d80d-11e4-9696-c7b5095c3332.jpg)

Arch Linux
Gnome 3.14
Vertex Theme downloaded from the [AUR](https://aur.archlinux.org/packages/vertex-themes/)

Thank for the awesome theme!

**Comment by horst3180** [comment]
Confirmed, I will fix this.

**Comment by horst3180** [comment]
Should be fixed with 22c91ae8643162fff1d203bdf4a71f30a3992a86
