### ISSUE TITLE
Vertex Dark Chromium Theme

### ISSUE THREAD

**Issue by samueljun** [horst3180/Vertex-theme#81]
Hey horst,

Was there a reason there isn't a Vertex Dark Chromium Theme?

Cheers

**Comment by samueljun** [comment]
I attempted my own implementation of the Vertex Dark theme following the color schemes of the Firefox Vertex Dark theme and the Chromium Vertex theme: cd67e69a89abd124781865e21e7f8df7b548f523

**Comment by horst3180** [comment]
See here: https://github.com/horst3180/Vertex-theme/issues/22
Dark Chrome themes just don't look right in my opinion. The theming options are too limited to make it look good with a dark theme.

**Comment by samueljun** [comment]
Ah I should have searched. Thanks for the reply
