### ISSUE TITLE
App Icon in Gnome-Shell-Theme

### ISSUE THREAD

**Issue by Tulpenzwiebel** [horst3180/Vertex-theme#83]
Hi,

is there any way to get the icon of the active application next to the Activities button in the shell bar back? I like these icons there.

Best regards,
Zwiebelchen

**Comment by michaelpmistretta** [comment]
Yeah, that is pretty easy. Edit the gnome-shell.css and change the properties for 'app-menu-icon' like this:

#panel .panel-button .app-menu-icon {
      -st-icon-style: symbolic;
      margin-left: 4px;
      margin-right: 4px; }

Save it, do ALT+F2 and type 'r' and you should have an app icon now. Keep in mind my example is for GNOME 3.16.

**Comment by Tulpenzwiebel** [comment]
Oh Yeah, this is really pretty easy. Thanks a lot!
I'm already using Gnome 3.16, I'm an Arch Linux user ;)
