### ISSUE TITLE
Non-CSD Titlebars

### ISSUE THREAD

**Issue by michaelpmistretta** [horst3180/Vertex-theme#84]
![vertex](https://cloud.githubusercontent.com/assets/11906224/7104268/39b72962-e099-11e4-8a81-112cb7b63d5f.png)

In 3.16 since Metacity was dropped the non-CSD windows look a little better when using Adwaita now, mostly due to the fact the titlebar is drawn with a border under it.

Vertex still draws a non-CSD window without the border under the titlebar. Any chance of adding this? I think it would look a lot better and non-CSD applications won't look so out of place.

Some extra padding would not hurt either here, since they are drawn rather thin in Vertex.

**Comment by horst3180** [comment]
Well, I think this is a matter of taste. I've styled the window decorations like this before and I see no reason why I should change it now. I've seen a lot of people complaining about the new adwaita decorations too, so there's no way to please everyone.

**Comment by michaelpmistretta** [comment]
Understandable, I just figured it may have been an oversight.
