### ISSUE TITLE
Window decoration in GNOME terminal looks wrong

### ISSUE THREAD

**Issue by pulb** [horst3180/Vertex-theme#86]
In GNOME 3.16 the window decoration of GNOME terminal looks wrong (no rounded corners). Please see the screenshot below.
![bildschirmfoto von 2015-04-12 13-49-59](https://cloud.githubusercontent.com/assets/827576/7105469/8527adea-e11b-11e4-85a3-b7872525e6e5.png)

**Comment by horst3180** [comment]
This is a mutter bug and it happens with Adwaita too. Here is the bug report https://bugzilla.gnome.org/show_bug.cgi?id=745060

**Comment by pulb** [comment]
I see, thanks again!

**Comment by horst3180** [comment]
FWIW it looks okay with the unpatched gnome-terminal. It seems to be a problem with certain window types.
