### ISSUE TITLE
Hide window controls like alt-metacity in GNOME 3.16

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [horst3180/Vertex-theme#87]
At the moment, window controls aren't controlled by metacity anymore in GNOME 3.16, it seems, so the alt-metacity theme without the maximized titlebars no longer works.

**Comment by horst3180** [comment]
This is no longer possible in Gnome 3.16. See https://github.com/horst3180/Vertex-theme/issues/68 for further information.
