### ISSUE TITLE
red "X"

### ISSUE THREAD

**Issue by derkens** [horst3180/Vertex-theme#89]
Hi, I just updated to gnome 3.16 on archlinux, I keep getting this red X on top of your window close button,
any idea?
![redx](https://cloud.githubusercontent.com/assets/642815/7139542/2f7baef2-e2c7-11e4-8b01-3763b84e8b52.png)

**Comment by horst3180** [comment]
Maybe it's an icon theme issue. Have you tried a different one?

**Comment by derkens** [comment]
wow, that was spot-on! awoken icons was the culprit...
thanks for your help, 
thanks for the great theme!
