### ISSUE TITLE
UbuntuGnome 15.04 Gtk3.16: GnomeShell Crash and Segfault

### ISSUE THREAD

**Issue by wolfland** [horst3180/Vertex-theme#92]
When using the Dash Applications and Logout/Shutdown I am getting a crash and segfault.

This is with a HP zt3300 laptop with radeon mobility 9200 video(software accel/render) and
the Vertex GnomeShell3.16 theme.
 
This problem does not occur on my QuadCore desktop with radeon 5550 video or on my 
Celeron desktop with radeon 9700 video which both use hardware accel/render.

This seems to be related to the dash applications launcher and logout/shutdown dialog as
far as I can tell and appears to be related to the software accel/rendering since it does not
occur on my hardware accelerated machines.

The default GnomeShell3.16 theme works without any issues.

Could this be related to the other GS crash issues from 3.12/3.14 ?

Here is the segfault(I have the full dmesg file if needed):
 844.811239] gnome-shell[1713]: segfault at 2b1869bf ip a6b9a493 sp bf92b640 error 4.

I may need to go back to 3.14 and flashback temporarily if Canonical comes up with fixes
for the 2 flashback problems I reported (the "black" panel problem and a metacity problem)
but I plan on running 3.16 until that happens and then afterwards since its working so well.

If I can find time in between keeping the 9 build/testing machines updated I will see if I can
figure out how to prop the gnome-shell-no-crash changes from 3.14 into 3.16 to see if they
will help.

Let me know if there is data I need to collect or if there is anything else I can do.

Thanks,
WolfLand

**Comment by horst3180** [comment]
Hmm yes, it seems to be the same problem that was apparent in the older versions. The logout/shutdown dialog crash is new, though.
I'll see if I can make some patches for this, but this doesn't solve the general problem. There is something wrong with gnome-shell or the gallium driver.

**Comment by wolfland** [comment]
I also was able to reproduce issues with Antergos 20150412 i686 running 
in live mode this morning.

I wanted to ensure that it was not an Ubuntu problem as I am pulling 
3.16 from the staging PPA
which is still considered unstable until 3.16.1 comes out (if the 
information I read is correct). The
Ubuntu implementation is still missing a few 3.16 apps like Nautilus 
which is still at 3.14.

Hopefully some of this will be addressed with 3.16.1 when it comes out.

I also should mention that I saw the problem occur with the sudo 
permission dialog (e.g. gksu etc)
as well as the logout/shutdown dialog so like you say it seems to be 
something general with GS or
the video driver when software acceleration is used.

Thanks for the help,
WolfLand

**Comment by horst3180** [comment]
It seems that this problem is even worse with Gnome 3.16. I tested the Ciliora-Secunda-Shell theme and it crashes the shell, too when opening the calendar menu.

**Comment by wolfland** [comment]
Yeah I am seeing some weirdness as well. The calender problem is not the 
"have to have the
week numbers turned on problem" maybe? I think I heard something like 
that but I always turn
them on anyway so I didn't really pay much attention to the actual 
problem description.

Just thought I should mention it.
WolfLand

**Comment by horst3180** [comment]
It's not the week number problem, it crashed with either setting.
On another note. I may have found a way to eliminate the crashes. I think they were occuring when I tried to override the style of the default theme and this particular style includes a box-shadow. Now I've found a different method to do this and I hope it will work.

**Comment by horst3180** [comment]
Ok, 0f51e8fd1cda1a14d81396230a230a8ea6a6a2a9 seems to fix the crashes (in my Fedora 22 vm atleast). I don't know if I caught everything, so if you could test it a bit, that would be great.

**Comment by wolfland** [comment]
I would be glad to. Do I pull the latest from git or prop your changes 
into the latest
released version?

Thanks,
WolfLand

**Comment by horst3180** [comment]
Just pull from git.

**Comment by wolfland** [comment]
Ok.. Tested on 3 Gtk3.16 machines. Everything works great on all three..

Thanks,
WolfLand

**Comment by horst3180** [comment]
Awesome! I'm so glad that this bug is finally fixed. I assume I can close this issue?

**Comment by wolfland** [comment]
Yes.. feel free to close the issue.

And thanks again for all  of your hard work,
WolfLand

**Comment by horst3180** [comment]
Okay, if you encounter another crash please reopen this issue.
