### ISSUE TITLE
Ubuntu 15.04 Vertex 20150418 does not work

### ISSUE THREAD

**Issue by wolfland** [horst3180/Vertex-theme#94]
Its me again. The new version of Vertex from 20140418 does not work.

The first problem is permissions are wrong after the sudo make install.
The read and execute permissions are not set for all users making
the theme either not visible or non-working(depending on the depth of
the directory/file permissions). I had to manually set the permissions
correctly per the instructions from the "old" install method to get the
theme first seen and then to work properly. I am not sure if this is an
"Ubuntu" thing or something more global. I have always had to check
and set the permissions after creating my installable versions so it may
be another "Ubuntu" quirk.

Secondly there is no portability. This makes it impossible to build versions on
one machine to be used on another. There needs to be an option to make a
zip file instead of just being forced to install. I have 10+ machines running
Vertex and not all are setup for build/compile.  Maybe you could add a "make
 zip" option.

Thirdly with Ubuntu (e.g. Unity desktop) changes are required to make Vertex
operate properly. Because of 15.04 release next week I just don't have time 
to learn sass right now, I have created 2 new files that I can piggyback onto
gtk-contained.css (the GTK approved method for extending themes) by just
adding their perspective import statements at the end of the file. This allows
me to override any default characteristics that I do not like as well as import
the changes required for Unity to work properly with minimal fuss. I will look
into sass as soon as I can after next week.

I understand you are trying to deal with the cumbersome install evident with
the previous version of Vertex. It normally takes me about 1 hour to take the
Vertex release (either from Git or GnomeLook.org) prop my changes and make
all of the versions I need into installable and portable versions for deployment 
and then another 1 hour to actually deploy them.

 I am certainly applaud your efforts to make the theme more easily deployable
and think with a few minor adjustments (like the zip option) this could really do
the trick.  

When 15.04 releases next week I should have more time to look into sass. 
Maybe I can get my 20 or so lines of .css ported to sass and add changes
to have sass add the 2 import statements needed at the end of the
gtk-contained.css files. If I can do this and you can add the zip option I can
use my 8-core daily driver to generate all of the needed zip files, burn a DVD
and then install the themes as I normally would.

You are really making great progress getting Vertex to be easily installable so
keep up the good work and thanks for all of your hard work. If you can think
of a better solution for my problem with portability please feel free to let me
know as I am always open to other solutions.

Thanks Again,
WolfLand

**Comment by wolfland** [comment]
After more thought and a quick test I found a workaround  for the portability issue:

If you set the "--prefix=" variable to some workdir you can install the theme to a working directory
for further editing or packaging. 

This is probably not the best solution but will work for now. I still think it would be handy to be
able to create a zip file from the make command.

In the mean time I will use the workaround.

I will look into converting my changes to sass as soon as I can after next weeks
15.04 release.

Thanks again for all of your hard work,
WolfLand

**Comment by horst3180** [comment]
The permissions should be correct. Did you clone the theme with git or downloaded it? 
Zip files don't store file permissions and this could be the problem here. So either clone with git or download a .tar.gz from the releases page. I don't know why github doesn't offer a tarball download for the current branch.

You can specify where to install the files. For example

    ./autogen.sh --datadir=$HOME
    make install

will create the directory `~/themes` with the contents `Vertex`, `Vertex-Light`  and `Vertex-Dark`. Probably you should use tar here too, to preserve the permissions.

Does the default Vertex need adjustments for Ubuntu 15.04? Last time I checked it worked fine.

**Comment by horst3180** [comment]
Have you thought about forking this theme on Github? You could make your changes in the forked repository once and then just sync it with upstream. This should be a lot faster.

**Comment by wolfland** [comment]
Ok. Must be the zip file thing that is causing the permissions problem. 
I always have to set the
permissions manually when I package before deploying. I almost always 
download either from
git or gnomelook.org so the file is always in zip format.

One interesting thing is that when I use the --prefix method and make 
install the permissions
are correct. Only when I used sudo make install to install to the 
/usr/share directory did I have
a problem. In the failure case the top level directory was set correctly 
but the subtending
directories were not set properly. It almost looked like a missing -R 
(e.g. recursive) directive
or something.

I figured out the --prefix path just after entering the bug report so I 
am good now.  I just have
to learn a bit of sass and I should be able to do things cleanly instead 
of hacking the .css files.

Thanks again for putting up with me,
WolfLand

**Comment by wolfland** [comment]
Actually I have thought about forking. The changes are about 40 lines of 
code so I
figured it might be more trouble that it was worth. I do upkeep my own 
version of
remastersys which is no longer supported and it might be a good idea to 
have a
place to park that too.

I'll add it to my list of things to do along with sass and check it out.

Thanks again,
WolfLand

**Comment by horst3180** [comment]
Ok, I found out that adding the `--no-preserve=mode,ownership` switch to the `cp` commands in makefile.am (c49e3682ed19b83a135dad0f33b77c5d4993ae19) seems to fix the permission problem when building and installing from the .zip file.

**Comment by wolfland** [comment]
Great.. I will pull the latest git when I get a chance.

I am also finding more stuff I can add to my git repository when I do it
(like a newly modified version of nouvegnomegray with more application 
icons).

I also plan to update the awesome AwOken Icon set to add more 
application icons
as well as get it updated for the latest gnome version. It turns out the 
version that
I have been using and extending is a hack of the original version and so 
the configuration
scripts no longer work with it.

I also have a huge artwork archive of wallpapers, themes, icons, cursors 
etc and should
put them up so that others can have access to them. Now that I have 2 
Bluray drives I
finally can back the archive up to disc.  Much of the stuff is very old 
but maybe someone
can get some ideas from them or use some of the pixmaps or something.

Thanks again for your hard work,
WolfLand
