### ISSUE TITLE
Lower part of gnome-terminal not used

### ISSUE THREAD

**Issue by Noxbru** [horst3180/Vertex-theme#95]
Hi, there's a little issue with your theme when using gnome-terminal (As far as I know, I haven't checked other terminals): The lower part of the window isn't used even when scrolling.

![issue](https://cloud.githubusercontent.com/assets/216686/7237533/089a439e-e794-11e4-8a8a-0a67e2dcfd8c.png)

**Comment by horst3180** [comment]
Are you using Gnome 3.14 or 3.16? It works fine for me with 3.16.

**Comment by Noxbru** [comment]
I am using Gnome 3.16.
I have also tried with Adwaita and it doesn't leave all that space... well, I think I can live with it. (BTW, I am using the stable release from 3 days ago, maybe something fixed this since then)

**Comment by horst3180** [comment]
Weird, for me it looks the same with Adwaita. I don't think the theme does something different than Adwaita when it comes to the terminal. Have you tried logging out and back in or resizing the terminal window a bit? Maybe something doesn't load correctly.
