### ISSUE TITLE
Gtk 2 issues

### ISSUE THREAD

**Issue by boobshart** [horst3180/Vertex-theme#97]
I installed Vertex from the AUR onto Antergos, with GNOME 3.16, and I'm experiencing issues with the theme in GTK2 apps. Vertex Dark & Light work as expected; there are only issues for the GTK2 of the normal theme. The window/panel/buttons don't seem to be functioning, nor much of the themed interface,  although some menus work properly.

**Comment by horst3180** [comment]
Could you show me some screenshots?

**Comment by boobshart** [comment]
OK never mind; I woke up this morning and changed the theme to take screenshots, but now it works. Thanks!
