### ISSUE TITLE
README.md suggestion

### ISSUE THREAD

**Issue by Sadi58** [horst3180/Vertex-theme#99]
I think it might be useful to include also the following option to "build and install the theme":

```
./autogen.sh --prefix=/home/<USER>/.local
make install
```
This also entails a similar option to uninstall.

**Comment by horst3180** [comment]
The problem with that is, that Gnome won't be able to find the gtk2 theme if it gets installed to `~/.local/share/themes`. The solution would be to symlink `~/.themes` to `~/.local/share/themes`, but this duplicates all entries in gnome-tweak-tool, and it is another step for the user to follow. I've had quite some bug reports of users who (understandably) didn't know this.

**Comment by Sadi58** [comment]
Haha, I was just wondering why Gnome Tweak Tool shows duplicates although Ubuntu Tweak Tool doesn't ;-)
